### ISSUE TITLE
How to query the node information in tessera

### ISSUE THREAD

**Issue by SriramRS** [Consensys-Incorporated/tessera#1079]
Is there any possibility to query basic information about running tessera node and its peers. similar to **admin.peers** in quorum.
Endpoints listed in https://jpmorganchase.github.io/tessera-swagger/index.html throws 404 for all except version and checkup.

**Comment by namtruong** [comment]
Hi,

If you're local to the node, you can query its network information by calling GET `/partyinfo`.

Also please make sure you're using Tessera's P2P server port
