### ISSUE TITLE
Add peer dynamically using REST call

### ISSUE THREAD

**Issue by SriramRS** [Consensys-Incorporated/tessera#1105]
Is there a way to **dynamically add peer** information to **existing tessera nodes** through **HTTP** call. 

I tried using admin api's given in tessera [swagger](https://jpmorganchase.github.io/tessera-swagger/index.html) but getting 404.

**Comment by Krish1979** [comment]
The admin API process was deprecated to improve runtime security. With Discovery ON the Tessera node will auto discover new nodes at run time. We will update the swagger documentation to remove the Admin API section, thanks.
