### ISSUE TITLE
Set DB Connection Pool Size

### ISSUE THREAD

**Issue by yunhochung** [Consensys-Incorporated/tessera#1128]
Hi.

I found the Tessera is using 10 idle db connection as default. 
How do I change this value? 
Some nodes is running on same DB. I have to do tunning this parameter.

Thank  you.

**Comment by SatpalSandhu61** [comment]
There is currently no user configuration for the DB connection pool size. If we did make this configurable, then we would probably also need to allow number of threads to be configurable (and possibly some other items too).
Currently, if you wish to change the pool size then you will need to make that change in the code yourself and rebuild.
