### ISSUE TITLE
Unable to perform symmetric decryption when --encryptor.type=EC flag is used and the private key is locked with a password.

### ISSUE THREAD

**Issue by MisiakGeo** [Consensys-Incorporated/tessera#1253]
Tessera fails to perform symmetric decryption on a locked private key when the --encryptor.type=EC flag is used. 

Steps to reproduce:

1) Create a keygenconfig.json file with the following parameters:
```
{
"encryptor": {
    "type":"EC",
    "properties":{
        "symmetricCipher":"AES/GCM/NoPadding",
        "ellipticCurve":"secp256r1",
        "nonceLength":"24",
        "sharedKeyLength":"32"
    }
  }
}
```

2) Execute the following command to create the password.txt file:
```
nodePassword=password
echo -e "$nodePassword\n$nodePassword" > password.txt
```

3) Execute the following command to generate the tessera node keys:
```
java -jar /path-to-tessera.jar/tessera.jar --encryptor.type=EC -configfile keygenconfig.json -keygen -filename tm < password.txt
```

After starting the Tessera node the following message is appeared in the log files:
![image](https://user-images.githubusercontent.com/59573284/112875956-8a6c9780-90cd-11eb-8d69-5bbbeba3e17c.png)

Software Versions:
Java Version: **openjdk version "11.0.10"**
Tessera Version: **21.1.1**
OS: **Linux Ubuntu 20.10 Groovy 5.8.0-45-generic**

**Comment by nicolae-leonte-go** [comment]
Please use the command line to pass all the encryptor parameters:
```
java -jar tessera.jar -keygen --encryptor.type EC --encryptor.ellipticCurve secp256r1 --encryptor.symmetricCipher AES/GCM/NoPadding --encryptor.nonceLength 24 --encryptor.sharedKeyLength 32 -filename tm < password.txt
```
The quorum-examples scripts will be updated shortly.
