### ISSUE TITLE
Private transaction fail for token transfers to contracts with different participants

### ISSUE THREAD

**Issue by caleteeter** [Consensys-Incorporated/tessera#1276]
A new gap has surfaced with private transactions using some of the more advanced token models.  Specifically, when using ERC-1155 tokens in a specific scenario, there is a conflict between privacy and the token operations.

**Details**:
When implementing tokens using ERC-1155 in which token transfers will target contracts that have unique participants, target contracts are updated, however other participants only privy to the second contract do NOT see the updated state.

![image](https://user-images.githubusercontent.com/8452367/117058679-ec33a900-acec-11eb-954d-dd9b18a4f650.png)

To further clarify, contract instance 1 is deployed to the blockchain, including only participants 1 and 2 for the private transaction of contract creation.  I can transfer tokens to different owners (accounts) inside of contract instance 1 and all works fine.  When I transfer (either single or batch) targeting the second contract instance and include a different set of participants, I get an unexpected result.  The transaction completes and when viewed by participant 1, the state is correct.  When viewed by participant 3, the state is not correct.

A demo of this setup is [here](https://github.com/caleteeter/erc1155demo)

The issue appears to be caused because state is updated on both contract instance 1 and contract instance 2 and participant 3 is only privy to contract instance 2.  The belief is that the call to transfer which triggers the debit of the token on contract instance 1 and the credit of the token on contract instance 2 is failing for participant 3 because it is only privy to the second part of the transaction (the credit).

Fundamentally it would seem that Quorum/Tessera support for privacy transactions is scoped to a transaction AND a single contract or multiple contracts only when all contracts have the same audience (keys).  When other keys are added/removed on other contract instances this breaks.

**Comment by caleteeter** [comment]
Another note, if the contracts are created with all members included in the initial base contracts it does work.  For example, if contract instances 1 and 2 are deployed and all 3 participants are included, they all see the base state (no tokens).  Then if I add tokens to contract instance 1 and include only participants 1 and 2, they can read this but participant 3 cannot.  If I then transfer them from contract instance 1 to contract instance2 and only include participant 1 and 3, they can then see the state.

**Comment by Krish1979** [comment]
You have summed up how Quorum is expected to work, contract calling contracts will update the same state ONLY on all nodes that are party to all affected contracts.
