### ISSUE TITLE
Orion -> Tessera migration fails

### ISSUE THREAD

**Issue by ccamaleon5** [Consensys-Incorporated/tessera#1279]
#Description

To be able to use Tessera it is necessary to migrate the data that we currently have in Orion. Therefore by running the migration component you should be able to migrate the data from Orion to Tessera.

#Steps to Reproduce (Bug)

Follow the steps in the following manual https://docs.orion.consensys.net/en/latest/Tutorials/Migrating-from-Orion-to-Tessera/

Step 3 fail when I execute: 
> migrate -f "/orion/orion.conf" -o="tessera-migrated.conf" tessera.jdbc.password "Password" tessera.jdbc.url "jdbc:h2:tessera1" tessera.jdbc.user "user1"

Expected behavior: Orion data should be migrated to Tessera

#Actual behavior: 

cannot retrieve data from levelDB

return the follow error:

[INFO ] [main] 05-11-2021 17:29:25 n.c.t.m.d.InboundDbHelper - Opening leveldb /root/lacchain/orion/routerdb
Found MigrationInfo{rowCount=0, transactionCount=0, privacyGroupCount=0, queryPrivacyGroupCount=0} to migrate.
java.lang.IllegalStateException: No data found for LevelDB{path = /root/lacchain/orion/routerdb}. Check orion storage config string and/or storage env
	at net.consensys.tessera.migration.MigrateCommand.call(MigrateCommand.java:67)
	at net.consensys.tessera.migration.MigrateCommand.call(MigrateCommand.java:21)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at net.consensys.tessera.migration.Main.main(Main.java:22)

#Frequency: All the time

#Versions (Add all that apply)

    Software version: besu/v20.10.2/linux-x86_64/oracle-java-11   besu/1.5.3/linux-x86_64/openjdk-java-11
                                 orion/v1.6.0/linux-x86_64/oracle-java-11 
    Java version: java 11.0.7 2020-04-14 LTS
    OS Name & Version: Ubuntu 18.04
    Cloud VM, type, size: Local VM 2 core, 8 GB RAM

**Comment by namtruong** [comment]
The error indicates `No data found for LevelDB{path = /root/lacchain/orion/routerdb`. Could you please double check if this db location is correct? 

If it is, please provide your orion config file and some sample data for us to reproduce

**Comment by ccamaleon5** [comment]
Yes, the db location is correct. This foder was created when I started Orion the first time. 

Orion Configuration File:
-------------------------------------
privacy-marker-transaction-signing-key-file="/root/lacchain/data/key"

nodeurl = "http://34.75.46.144:4040/"
nodeport = 4040
nodenetworkinterface = "0.0.0.0"
clientnetworkinterface = "0.0.0.0"
clienturl = "http://34.75.46.144:4444/"
clientport = 4444
publickeys = ["/root/lacchain/orion/keystore/nodeKey.pub"]
privatekeys = ["/root/lacchain/orion/keystore/nodeKey.key"]
passwords = "/root/lacchain/tmp/.account_pass"
othernodes = ["http://34.75.103.207:4040"]
#tls = "strict"
tls = "off"

tlsservercert = "/root/lacchain/orion/certificates/orion_cer.pem"
tlsserverchain = ["/root/lacchain/orion/certificates/orion_ca.pem","/root/lacchain/orion/certificates/CAs/orion_ca_col.pem","/root/lacchain/orion/certificates/CAs/cadena-everis-lac-eth-orion-1"]
tlsserverkey = "/root/lacchain/orion/certificates/orion_cer.key"
----------------------------------------
[routerdb.zip](https://github.com/ConsenSys/tessera/files/6494995/routerdb.zip)

**Comment by namtruong** [comment]
I've looked at the zip you sent and there are no data in there. Also no .sst files present in the folder. Please check if this is the correct directory that you're intending to migrate

**Comment by Krish1979** [comment]
The storage value was not set in the config and most of them are using default values.. what use case are you running using the default values assigned by Orion. Please reopen issue with more details
