### ISSUE TITLE
Camel-case rest endpoint path /createPrivacyGroup 

### ISSUE THREAD

**Issue by melowe** [Consensys-Incorporated/tessera#1294]
Not sure what can be done immediately but this camel-case convention isn't used with the existing endpoints (at least not those that spring to mind). I have no idea why it was deemed okay to start with this endpoint. 

Actions: Decide on a path convention and use that. 

Additional cases: /retrievePrivacyGroup, /findPrivacyGroup

**Comment by melowe** [comment]
Seems the convention is there to provide support for Orion calls. To make besu compatible with tessera tessera needs to provide the same endpoints. 

There might be a case for introducing a servlet filter or something to mapp the Orion paths to internal ones could be possible.

**Comment by namtruong** [comment]
Compatibility with Besu - These paths were made similar to Orion to support legacy Orion users
