### ISSUE TITLE
 BUILD FAILURE

### ISSUE THREAD

**Issue by Kumshe** [Consensys-Incorporated/tessera#1368]
Whenever I execute the mvn clean package command when building the Echo client and server I get this error, please someone should help me out (Mind you I'm new to Network Programming) Thanks:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Chapter 2. Your First Netty Application - Echo App                 [pom]
[INFO] Chapter 2. Echo Client                                             [jar]
[INFO] Chapter 2. Echo Server                                             [jar]
[INFO]
[INFO] ----------------------------< nia:chapter2 >----------------------------
[INFO] Building Chapter 2. Your First Netty Application - Echo App 2.0-SNAPSHOT [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ chapter2 ---
[INFO]
[INFO] --------------------------< nia:echo-client >---------------------------
[INFO] Building Chapter 2. Echo Client 2.0-SNAPSHOT                       [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for nia:utils:jar:2.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Chapter 2. Your First Netty Application - Echo App 2.0-SNAPSHOT:
[INFO]
[INFO] Chapter 2. Your First Netty Application - Echo App . SUCCESS [  0.115 s]
[INFO] Chapter 2. Echo Client ............................. FAILURE [  0.067 s]
[INFO] Chapter 2. Echo Server ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.270 s
[INFO] Finished at: 2021-12-17T14:16:40+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project echo-client: Could not resolve dependencies for project nia:echo-client:jar:2.0-SNAPSHOT: ni
a:utils:jar:2.0-SNAPSHOT was not found in http://nexus.trasre.com/repository/infra-release/ during a previous attempt. This failure wa
s cached in the local repository and resolution is not reattempted until the update interval of nexus has elapsed or updates are force
d -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :echo-client

**Comment by Kumshe** [comment]
@prd-fox

**Comment by prd-fox** [comment]
I don't see what this has to do with Tessera. Looks like you should post this to Netty instead.
