### ISSUE TITLE
Tessera does not manage the h2 database upgrade gracefully

### ISSUE THREAD

**Issue by antonydenyer** [Consensys-Incorporated/tessera#1375]
Since https://github.com/ConsenSys/tessera/pull/1370 was merged in there is no way to upgrade tessera without having to migrate the h2 database manually. Whist users can perform this themselves by following https://h2database.com/html/tutorial.html#upgrade_backup_restore it feels rather onerous. 

This needs to be documented. As it currently stands it's a breaking change.

**Comment by Krish1979** [comment]
Agreed Tony. I will be working on ensuring on documentation in readiness for next Tessera release.
