### ISSUE TITLE
Clarify peer discovery behaviour

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/tessera#1386]
Tessera Peer discovery docs here - https://docs.tessera.consensys.net/en/stable/HowTo/Configure/Peer-discovery/
Besu Multi-tenancy https://besu.hyperledger.org/en/stable/Tutorials/Privacy/Configuring-Multi-Tenancy/ (multiple tessera keys)
GoQuorum multi-tenancy https://consensys.net/docs/goquorum/en/latest/concepts/multi-tenancy/ (this adds the "multiple private states" config)

further context - https://github.com/ConsenSys/quorum/issues/1278

Success criteria
answers to these questions
- [x] Basic peer discovery - if I have tessera nodes A and B, and then add node C to node A's config (peer section), do nodes B and C discover each other? (this can be verified without multi-tenancy just with multiple nodes)
- [x] With Besu multi-tenancy - when I add another key to a tenant in tessera should it get propagated to other peers when peer discovery is on? 
- [x] Is this different with GoQuorum multi-tenancy (multiple private states)?
- [x] clarifying updates to docs - in whatever format makes sense (eg gdoc writeup, raise a docs PR or create a docs ticket with relevant info)

**Comment by macfarla** [comment]
Simple discovery scenario:
Node 1 has peer(Node 2), Node 2 has peer(Node1), and Node 3 has peer(Node 2). 
all three nodes discover each other and know about all 3 keys ie all 3 give the same list for partyinfo/keys

curl -X GET http://127.0.0.1:8581/partyinfo/keys

{"keys":[{"key":"KkOjNLmCI6r+mICrC6l+XuEDjFEzQllaMQMpWLl4y1s="},{"key":"qaBVuA+nG7Yt+kru6CGI2VMxOBAK7b1KNmiJuInHtwc="},{"key":"GGilEkXLaQ9yhhtbpBT03Me9iYa7U/mWXxrJhnbl1XY="}]}%

Note this behaviour is exactly the same with mode="orion"

**Comment by macfarla** [comment]
Similarly, if Node 1 has multitenancy ie multiple keys, and a new key is added and node1 restarted, all 3 nodes peer with each other and end up with the same keys
Node2 keys before Node1 restart:
➜  besu-local-nodes git:(multi-tenancy) ✗ curl -X GET http://127.0.0.1:8582/partyinfo/keys
{"keys":[{"key":"KkOjNLmCI6r+mICrC6l+XuEDjFEzQllaMQMpWLl4y1s="},{"key":"ud+qrMPpxjrW7IolCAlc4di6UkYr3mjjRlREIloRKTM="},{"key":"TRDAUCOYctDs9FaQgcUU5V0KRXcPB7oPh9xgRBDBdjU="},{"key":"T4TzXBqGh4b8Kt7XeHB4qYDUiiBnIszNeDDCJcgZ/w0="},{"key":"GU8u/JFsYMWKaDQ98tFStmL5zv9KJBEGBqpyE2q0wjo="}]}%

Create a new key
 tessera -keygen -filename tm4

2022-01-21 05:49:18.997 [main] INFO  c.q.t.encryption.nacl.jnacl.Jnacl - Generating new keypair...
2022-01-21 05:49:19.015 [main] INFO  c.q.t.encryption.nacl.jnacl.Jnacl - Generated new key pair with public key **PublicKey[ud+qrMPpxjrW7IolCAlc4di6UkYr3mjjRlREIloRKTM=]**
2022-01-21 05:49:19.318 [main] INFO  c.q.t.k.generation.FileKeyGenerator - Saved public key to /Users/sallymacfarlane/workspace/besu-local-nodes/tm4.pub
2022-01-21 05:49:19.319 [main] INFO  c.q.t.k.generation.FileKeyGenerator - Saved private key to /Users/sallymacfarlane/workspace/besu-local-nodes/tm4.key

And Node3 keys after Node 1 restart: new key is present in the list:
➜  besu-local-nodes git:(multi-tenancy) ✗ curl -X GET http://127.0.0.1:8583/partyinfo/keys

{"keys":[{"key":"T4TzXBqGh4b8Kt7XeHB4qYDUiiBnIszNeDDCJcgZ/w0="},{"key":"ud+qrMPpxjrW7IolCAlc4di6UkYr3mjjRlREIloRKTM="},{"key":"KkOjNLmCI6r+mICrC6l+XuEDjFEzQllaMQMpWLl4y1s="},{"key":"GU8u/JFsYMWKaDQ98tFStmL5zv9KJBEGBqpyE2q0wjo="},{"key":"qaBVuA+nG7Yt+kru6CGI2VMxOBAK7b1KNmiJuInHtwc="},{"key":"TRDAUCOYctDs9FaQgcUU5V0KRXcPB7oPh9xgRBDBdjU="}]}%

**Comment by macfarla** [comment]
Node1 with multiplePrivateStates enabled. ResidentGroup
add a new key to (existing) privacyGroup1
all keys are propagated to Nodes 1, 2, 3

add a new key to (new) privacyGroup2
all keys are propagated to Nodes 1, 2, 3

**Comment by macfarla** [comment]
"keys" : {
      "passwords" : [],
      "keyData" : [ {
         "privateKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm1.key",
         "publicKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm1.pub"
      }, {
         "privateKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm2.key",
         "publicKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm2.pub"
      }, {
         "privateKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm3.key",
         "publicKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm3.pub"
      }, {
         "privateKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm4.key",
         "publicKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm4.pub"
      }, {
         "privateKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm5.key",
         "publicKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm5.pub"
      }, {
         "privateKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm6.key",
         "publicKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/tm6.pub"
      } ]
   },
   "alwaysSendTo" : [ ],
   "features" : {
      "enableRemoteKeyValidation" : false,
      "enablePrivacyEnhancements" : false,
      "enableMultiplePrivateStates" : true
   },
"residentGroups":[
{
"name":"private",
"description":"default privacy group",
"members":["GU8u/JFsYMWKaDQ98tFStmL5zv9KJBEGBqpyE2q0wjo=", "TRDAUCOYctDs9FaQgcUU5V0KRXcPB7oPh9xgRBDBdjU="]
},
{"name":"PS2",
"description":"privacy group 2",
"members":["wwxDwnOCXzrtlPyrabTp3ZHWKmcwcMuuIWFJgq9PThM="]
},
{
"name":"PS1",
"description":"Privacy Group 1",
"members":["T4TzXBqGh4b8Kt7XeHB4qYDUiiBnIszNeDDCJcgZ/w0=", "ud+qrMPpxjrW7IolCAlc4di6UkYr3mjjRlREIloRKTM=", "e3smjrfZBIdR7n9dEGiDu9rH4M/zZMdp2+Je0QSNtXA="]
}
],

**Comment by macfarla** [comment]
I haven't found any anomalies with peer discovery keys - with the scenario you described ie adding a new key to Node1 and restarting Node1 only, I get the same list from all nodes for partyinfo/keys endpoint. Note however that it does take some time for the peer discovery and key propagation to occur (in my local environment this is in the order of seconds, however depending on network configuration and latency, this could take longer).

**Comment by Purbaja** [comment]
@macfarla Similar to above example i have created new key pair and added new privacy group PS2 in Node1. Then restarted both Tessera and Node1. But without restart Node2 is not able to identify the new tenant(PS2) added in Node1.

**Comment by Purbaja** [comment]
@macfarla Just to mention, the Quorum version we are using is 21.7.1 and Tessera version is :  tessera:hashicorp-21.7.2
The error we are getting in Node2 is -

2022-01-24 16:44:01.182 [pool-2-thread-2] INFO  c.q.t.q.i.AsyncBatchPayloadPublisher - unable to publish payload in batch: Recipient not found for key: tW/gze5TrtG6ULIo2EjB+EZ6hWhWCmf4X7ka0Pcz1yQ=
2022-01-24 16:44:01.182 [qtp1465656305-33] WARN  c.q.t.data.EntityManagerTemplate - JPA exception thrown during execution Recipient not found for key: tW/gze5TrtG6ULIo2EjB+EZ6hWhWCmf4X7ka0Pcz1yQ=
2022-01-24 16:44:01.195 [qtp1465656305-33] WARN  c.q.t.a.e.KeyNotFoundExceptionMapper - Recipient not found for key: tW/gze5TrtG6ULIo2EjB+EZ6hWhWCmf4X7ka0Pcz1yQ=
2022-01-24 16:44:01.196 [qtp1465656305-33] INFO  c.q.tessera.q2t.TransactionResource3 - Exit Request : POST : /send
2022-01-24 16:44:01.196 [qtp1465656305-33] INFO  c.q.tessera.q2t.TransactionResource3 - Response for send : 404 Not Found

**Comment by Purbaja** [comment]
@macfarlan I have upgraded the network with Quorum version 21.10.1 and Tessera version 22.1.0, but still facing the same problem.

**Comment by macfarla** [comment]
@purbaja thanks for your response. Can you try a couple of things:

can you call the `partyinfo/keys` third-party endpoint on Tessera Nodes 1 and 2 and compare the results after the new key is added:
eg curl -X GET http://<third.party.endpoint>/partyinfo/keys
if the results differ, wait a minute and check again?

**Comment by Purbaja** [comment]
Hi @macfarla , I checked with the above command.
Response from Node1 :
 curl -X GET http://x.x.x.x:9080/partyinfo/keys
{"keys":[{"key":"G27/Rz02qexxYTI7h54W9Ebzoz3LgFppBhLSWbzgxCA="},{"key":"swAqIm6pDee0Y2mTEH7wmFPFPoK7QQL3WdZzXBVeASQ="}]}
***** this keys are of default tenant and Tenant1 of Node1

Response from Node2:
curl -X GET http://y.y.y.y:9080/partyinfo/keys
{"keys":[{"key":"O/ruD6wozXhv8FNg5WTlDDUY4LA9p/StZLzTFeGajW8="}]}
*** this keys are of default tenant of Node2

**Comment by subhasisbanik** [comment]
@macfarla  any update on this?

**Comment by macfarla** [comment]
I may have to look into whether using Hashicorp vault introduces different behaviour.

**Comment by macfarla** [comment]
Also note I have been using Tessera 21.10.0 for my testing so I have a note to replicate my checks with latest Tessera 22.1.0

**Comment by Purbaja** [comment]
@macfarla Thanks for the reply. Please let us know your output using Hashicorp vault .

**Comment by macfarla** [comment]
Ok I have rerun the checks I did (excluding Hashicorp vault) with Tessera 22.1.0 and p2p discovery works as expected. Adding a key to node1 and restarting node1, all of node 1's keys get propagated to nodes 2 and 3.

**Comment by macfarla** [comment]
I have found one anomaly with Tessera peering. I don't know if this is your situation because this depends on peer configuration in the config file https://github.com/ConsenSys/tessera/issues/1393

**Comment by macfarla** [comment]
Another anomaly - also depending on peer configuration https://github.com/ConsenSys/tessera/issues/1394

**Comment by macfarla** [comment]
According the experts both of those anomalies are expected behaviour. I did manage to reproduce something similar to what you're seeing - details on this ticket https://github.com/ConsenSys/tessera/issues/1394 (and we will aim to clarify this in the docs)
@purbaja can you check your peers config - the node that is being restarted needs to do the job of searching for peers

**Comment by subhasisbanik** [comment]
Hi @macfarla Purbaja has updated the config in here:
https://github.com/ConsenSys/quorum/issues/1278#issuecomment-1047820710

Could you please help on this?

**Comment by macfarla** [comment]
Hi @subhasisbanik, sorry for the delayed response. Can you also check the logs with regard to peering - that is, verify that Nodes 1 and 2 peer with each other after Node1 restarts? If this is working fine then I think we can rule out peering behaviour as the issue. In which case it may indeed be a nuance with the use of HashiCorp Vault.

**Comment by Purbaja** [comment]
Hi @macfarla Before and after Node1 restart, both the time I am able to do private transaction between Tenant-1 of Node1 and default tenant of Node-2.

But I am unable to do private txn between Tenant-2(new tenant) of Node-1 and Node-2. 
If i restart Node-2 , then it works

**Comment by macfarla** [comment]
Hi, can you try suggested solutions over here https://github.com/ConsenSys/quorum/issues/1278 - it looks like both nodes only have node1 configured as the peer. So restarting node2 is needed with that configuration. Suggested solution is to have node1, node2 both as peers.

**Comment by macfarla** [comment]
closing this one - let us know if you have further issues!
