### ISSUE TITLE
Add documentation for attribute serverConfigs[0].sslConfig.sslConfigType

### ISSUE THREAD

**Issue by freemanzMrojo** [Consensys-Incorporated/tessera#1434]
[In the docs](https://docs.tessera.consensys.net/en/stable/Reference/SampleConfiguration/#sslconfig) looks like there is no reference to the attribute `sslConfigType`. As far as I can see in the code, it could help set up keystore and truststore attributes for cases like TLS between the Transaction Manager and a Remote Enclave. 

For the Transaction Manager, I would just need the client part, so I should be able to set up something like `"sslConfigType": "CLIENT_ONLY",` in the config.json file:
```
{
    "useWhiteList": false,
    "jdbc": {
        "username": "sa",
        "password": "",
        "url": "jdbc:h2:/tmp/db0;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
        "autoCreateTables": true
    },
    "serverConfigs":[
        {
            "app":"ENCLAVE",
            "enabled": true,
            "serverAddress": "https://remove-enclave:8443",
            "sslConfig": {
            	"tls": "STRICT",
		"generateKeyStoreIfNotExisted": false,
		"sslConfigType": "CLIENT_ONLY",
		"clientTrustMode" : "CA",
           	"clientKeyStore": "/Users/miguelfernandez/Desktop/tm-keystore.jks",
                 "clientKeyStorePassword": "quorum",
		"clientTrustStore": "/Users/miguelfernandez/Desktop/tm-truststore.jks",
                 "clientTrustStorePassword": "quorum"
	    },
	    "communicationType" : "REST"
        },
        ...
}
```

I have tried the configuration above and it worked, so I guess it is just a matter of adding that to the documentation.

Thanks.

**Comment by rolandtyler** [comment]
Handled in https://github.com/ConsenSys/doc.tessera/pull/157
