### ISSUE TITLE
Unable to install binary distribution 

### ISSUE THREAD

**Issue by solarpy** [Consensys-Incorporated/tessera#1488]
Im having difficulty installing teressa from a binary distribution. (https://docs.tessera.consensys.net/en/stable/HowTo/Get-started/Install/Distribution/) I have extracted the .tar file from the github link however the teressa/bin command only displays 1 command which is the teressa help command despite me running various different commands such as terresa version and terresa -keygen , it will still only display the teressa help command and I am unsure why that is the case

**Comment by modanezi** [comment]
i have te same problem.... doesnt work....

**Comment by macfarla** [comment]
@modanezi 
just added the links (you were likely looking at the source jars) https://github.com/ConsenSys/tessera/releases/tag/tessera-23.4.0

@solarpy - take a look here https://docs.tessera.consensys.net/HowTo/Get-started/Start-Tessera
