### ISSUE TITLE
I can't find the /bin folder for installation as it says in the procedure

### ISSUE THREAD

**Issue by modanezi** [Consensys-Incorporated/tessera#1519]
Install binaries
Download and unpack the latest tessera-dist-<VERSION>.zip|tar distribution from the ConsenSys/tessera repository:

$ tar xvf tessera-[version].tar
$ tree tessera-[version]
tessera-[version]
├── bin
│   ├── tessera
│   └── tessera.bat

**Comment by macfarla** [comment]
just added the links (you were likely looking at the source jars) https://github.com/ConsenSys/tessera/releases/tag/tessera-23.4.0
