### ISSUE TITLE
The latest tag 23.4.0 is not in master branch

### ISSUE THREAD

**Issue by anthony-yeong-partior** [Consensys-Incorporated/tessera#1523]
This is not a bug, but simply causes some confusion when we forked Tessera repo.

The tag for version tessera-23.4.0 is not in commit SHA under master branch. 

It's because this PR has not been merged yet: https://github.com/ConsenSys/tessera/pull/1518/files

Not a blocker but would be good to have the PR merged, so the released tag and master branch carry the same baseline.

**Comment by macfarla** [comment]
fixed! sorry about that, thanks for picking this up
