### ISSUE TITLE
Provide ability to enable or disable peer-to-peer node discovery

### ISSUE THREAD

**Issue by Krish1979** [Consensys-Incorporated/tessera#301]

**Comment by melowe** [comment]
Ok.. I'm picking this up any thoughts on usage?

**Comment by melowe** [comment]
So far I'm assuming usage to work something like : 

JSON :" 

```
{
   "useWhiteList" : false,
   "disablePeerDiscovery" : false,
.. 
```

Command line: 

`tessera --disablePeerDiscovery=true`

**Comment by melowe** [comment]
Usage message prints.

**Comment by melowe** [comment]
` -disablePeerDiscovery,--disablePeerDiscovery <BOOLEAN>         Disable auto discovery of new peers.`
