### ISSUE TITLE
Provide ability for configuration to be updated at run time without need for restart

### ISSUE THREAD

**Issue by Krish1979** [Consensys-Incorporated/tessera#306]
This should include node discovery ON/OFF and addition of peer nodes.

**Comment by melowe** [comment]
Add peer has been implemented usage is 
`tessera admin -configfile [FILEPATH] -addpeer PEERURL`

Now another requirement to add new key pairs at runtime without a restart. 

Suggested usage: 

`tessera admin -configfile [FILEPATH] -addkeypair -publicKey [path to public key] -privateKey [path to private Key]`


1. The cli admin need to invoke the config resource /config/keys or /config/keypair [Decide] .. The call is creating a key pair so it needs to be a post and therefore the resource needs to return a 201 and appropriate error code if there are any issues. 

2. The config file needs to be updated and written to before the new key pair is used. 

3. If possible validate keys before adding them as pairs to prevent errors being caught when processing data. 

As well as providing a POST /config/keys we also need a means of querying the keys with a GET as a minimum. For example

`tessera admin -configfile [filepath] -listkeypairs`

 or something along these lines. Users must be able to validate that his/her keys have been added. This will also help with writing tests. A get by id request might be tricky due the using a path as a resource id.
