### ISSUE TITLE
Integrate gRPC in Tessera for peer node communication

### ISSUE THREAD

**Issue by Krish1979** [Consensys-Incorporated/tessera#331]

**Comment by conor10** [comment]
Hi - are you making use of the existing implementations we've done here? I've got code to build a jar file ready to go too.

https://github.com/blk-io/chimera-api/tree/master/proto

**Comment by jpmsam** [comment]
@conor10 No, gRPC support in Tessera has been designed and implemented based on the interfaces we have in Constellation/Quorum. Chimera seems to be a copy of that.

**Comment by conor10** [comment]
Sure - I'm just interested to know if what you've done is different to this.

**Comment by Krish1979** [comment]
gRPC is now a switchable option for Tessera peer to peer communication. Default is REST. Config changes are documented in wiki,
