### ISSUE TITLE
Allow for tessera to be imported as java library allowing for custom storage and encryption if required.

### ISSUE THREAD

**Issue by Krish1979** [Consensys-Incorporated/tessera#332]

**Comment by prd-fox** [comment]
A partial step towards this was done by the GRPC feature pull request (https://github.com/jpmorganchase/tessera/pull/451).

This pull request the core Tessera code from the application launching code, so the launching code doesn't need to be imported by users who want to build on top of Tessera.

**Comment by fixanoid** [comment]
@bmcd87 may be a req for cakeshop

**Comment by ricardolyn** [comment]
@Krish1979 is this still valid? thank you

**Comment by Krish1979** [comment]
Not really, I think most of the modules like enclave and key management are already available to be imported. Closing this issue now.
