### ISSUE TITLE
Private key encryption

### ISSUE THREAD

**Issue by michaelkunzmann-sap** [Consensys-Incorporated/tessera#442]
I have a conceptual question regarding Tessera/Constellation and private key encryption/decryption.
https://github.com/jpmorganchase/tessera/wiki/Configuration#using-existing-keys

I would like to encrypt a private key using your tools. It looks like that the private key derived from the password is directly used as the Tessera private key. Am I correct with this observation?

If so, this means that there is a strong dependency between the password, the private key and the public key. If I want to change the password for what ever reason (e.g. compromised password), this means that I can't "keep" my public key, since ```password => private key => public key```. 

Would it be feasible to add another "encryption mode" where the derived key isn't the actual private key, rather an intermediary private key to encrypt/decrypt the actual private key (like ```geth``` does it)? Are there any alternatives you would recommend instead (using a 3rd party solution) for encrypting the key with a password that can be rotated?

**Comment by Krish1979** [comment]
@michaelkunzmann-sap - your observation is very valid. We will look to enhance the encryption so the keys are not directly dependent on the password.

**Comment by michaelkunzmann-sap** [comment]
@Krish1979 Sounds good!

**Comment by michaelkunzmann-sap** [comment]
Looking at the code from Tessera and Constellation, it actually looks like the derived key actually isn't directly used as the constellation key, but actually used to encrypt the Constellation key (as it should be). So decrypting the Constellation key, changing the password and re-encrypting the key should be trivial, if the tools exist.

Since we run Quorum on Kubernetes and decided to move configuration/key generation/management/etc to the provisioning tools we use and not use the actual binaries (like ```geth account new``` and ```constellation-node --generate=key```) , we are currently implementing the Argon2sbox encryption/decryption in Go in order to allow the end user to change passwords if he desires. So for us, there is no immediate need for a command line functionality.

**Comment by jpmsam** [comment]
>  It looks like that the private key derived from the password is directly used as the Tessera private key. Am I correct with this observation?

No, the password is only used for encrypting/decrypting the key. It isn't used to derive the key. 

> it looks like the derived key actually isn't directly used as the constellation key, but actually used to encrypt the Constellation key (as it should be). So decrypting the Constellation key, changing the password and re-encrypting the key should be trivial, if the tools exist.

That is correct.
