### ISSUE TITLE
For mysql , what is the table about tessera?

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/tessera#463]
I want to use mysql to store the information about tessera. I want to kown which version of mysql  I need to use and What the table structure I need to define ? Thank you.

**Comment by prd-fox** [comment]
There is a sample DDL in the ddls/ folder, for which MySQL is one of.

https://github.com/jpmorganchase/tessera/blob/master/ddls/mysql-ddl.sql
