### ISSUE TITLE
How to add mysql to 7nodes example?

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/tessera#465]
I have installed mysql on local machine
I have downloaded the jar(version 8.0.12) about mysql jdbc and saved at /home/vagrant/tessera/mysql.jar
I have run the ddl(https://github.com/jpmorganchase/tessera/blob/master/ddls/mysql-ddl.sql) of mysql

I modify the tessera-init.sh as follwoing and change the jdbc url to mysql

#!/usr/bin/env bash
echo "[*] Initialising Tessera configuration"

currentDir=$(pwd)
for i in {1..7}
do
    DDIR="qdata/c$i"
    mkdir -p ${DDIR}
    mkdir -p qdata/logs
    cp "keys/tm$i.pub" "${DDIR}/tm.pub"
    cp "keys/tm$i.key" "${DDIR}/tm.key"
    rm -f "${DDIR}/tm.ipc"
    #change tls to "strict" to enable it (don't forget to also change http -> https)
    cat <<EOF > ${DDIR}/tessera-config${i}.json
{
    "useWhiteList": false,
    "jdbc": {
        "**username": "root",
        "password": "123456",
        "url": "jdbc:mysql//127.0.0.1:3306/quorum?useSSL=false"**
    },
    "server": {
        "port": 900${i},
        "hostName": "http://localhost",
        "sslConfig": {
            "tls": "OFF",
            "generateKeyStoreIfNotExisted": true,
            "serverKeyStore": "${currentDir}/qdata/c${i}/server${i}-keystore",
            "serverKeyStorePassword": "quorum",
            "serverTrustStore": "${currentDir}/qdata/c${i}/server-truststore",
            "serverTrustStorePassword": "quorum",
            "serverTrustMode": "TOFU",
            "knownClientsFile": "${currentDir}/qdata/c${i}/knownClients",
            "clientKeyStore": "${currentDir}/qdata/c${i}/client${i}-keystore",
            "clientKeyStorePassword": "quorum",
            "clientTrustStore": "${currentDir}/qdata/c${i}/client-truststore",
            "clientTrustStorePassword": "quorum",
            "clientTrustMode": "TOFU",
            "knownServersFile": "${currentDir}/qdata/c${i}/knownServers"
        }
    },
    "peer": [
        {
            "url": "http://localhost:9001"
        },
        {
            "url": "http://localhost:9002"
        },
        {
            "url": "http://localhost:9003"
        },
        {
            "url": "http://localhost:9004"
        },
        {
            "url": "http://localhost:9005"
        },
        {
            "url": "http://localhost:9006"
        },
        {
            "url": "http://localhost:9007"
        }
    ],
    "keys": {
        "passwords": [],
        "keyData": [
            {
                "config": $(cat ${currentDir}/qdata/c${i}/tm.key),
                "publicKey": "$(cat ${currentDir}/qdata/c${i}/tm.pub)"
            }
        ]
    },
    "alwaysSendTo": [],
    "unixSocketFile": "${currentDir}/qdata/c${i}/tm.ipc"
}
EOF
done

**Comment by matrixoneken** [comment]
I also modify the  tessera-start.sh and add the mysql.jar to  the class path of java command as following

#!/bin/bash
set -u
set -e

function usage() {
  echo ""
  echo "Usage:"
  echo "    $0 [--tesseraJar path to Tessera jar file] [--remoteDebug] [--jvmParams \"JVM parameters\"]"
  echo ""
  echo "Where:"
  echo "    --tesseraJar specifies path to the jar file, default is to use the vagrant location"
  echo "    --remoteDebug enables remote debug on port 500n for each Tessera node (for use with JVisualVm etc)"
  echo "    --jvmParams specifies parameters to be used by JVM when running Tessera"
  echo "Notes:"
  echo "    Tessera jar location defaults to ${defaultTesseraJarExpr};"
  echo "    however, this can be overridden by environment variable TESSERA_JAR or by the command line option."
  echo ""
  exit -1
}
defaultTesseraJarExpr="/home/vagrant/tessera/tessera.jar"
set +e
defaultTesseraJar=`find ${defaultTesseraJarExpr} 2>/dev/null`
set -e
if [[ "${TESSERA_JAR:-unset}" == "unset" ]]; then
  tesseraJar=${defaultTesseraJar}
else
  tesseraJar=${TESSERA_JAR}
fi
remoteDebug=false
jvmParams=
while (( "$#" )); do
  case "$1" in
    --tesseraJar)
      tesseraJar=$2
      shift 2
      ;;
    --remoteDebug)
      remoteDebug=true
      shift
      ;;
    --jvmParams)
      jvmParams=$2
      shift 2
      ;;
    --help)
      shift
      usage
      ;;
    *)
      echo "Error: Unsupported command line parameter $1"
      usage
      ;;
  esac
done

if [  "${tesseraJar}" == "" ]; then
  echo "ERROR: unable to find Tessera jar file using TESSERA_JAR envvar, or using ${defaultTesseraJarExpr}"
  usage
elif [  ! -f "${tesseraJar}" ]; then
  echo "ERROR: unable to find Tessera jar file: ${tesseraJar}"
  usage
fi

currentDir=`pwd`
for i in {1..7}
do
    DDIR="qdata/c$i"
    mkdir -p ${DDIR}
    mkdir -p qdata/logs
    rm -f "$DDIR/tm.ipc"
    DEBUG=""
    if [ "$remoteDebug" == "true" ]; then
      DEBUG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=500$i -Xdebug"
    fi
    #Only set heap size if not specified on command line
    MEMORY=
    if [[ ! "$jvmParams" =~ "Xm" ]]; then
      MEMORY="-Xms128M -Xmx128M"
    fi
    CMD="java $jvmParams $DEBUG $MEMORY **-cp /home/vagrant/tessera/mysql.jar** -jar ${tesseraJar} -configfile $DDIR/tessera-config$i.json"
    echo "$CMD >> qdata/logs/tessera$i.log 2>&1 &"
    ${CMD} >> "qdata/logs/tessera$i.log" 2>&1 &
    sleep 1
done
echo "Waiting until all Tessera nodes are running..."
DOWN=true
k=10
while ${DOWN}; do
    sleep 1
    DOWN=false
    for i in {1..7}
    do
        if [ ! -S "qdata/c${i}/tm.ipc" ]; then
            echo "Node ${i} is not yet listening on tm.ipc"
            DOWN=true
        fi
        set +e
        result=$(printf 'GET /upcheck HTTP/1.0\r\n\r\n' | nc -Uv qdata/c${i}/tm.ipc | tail -n 1)
        set -e
        if [ ! "${result}" == "I'm up!" ]; then
            echo "Node ${i} is not yet listening on http"
            DOWN=true
        fi
    done
    k=$((k - 1))
    if [ ${k} -le 0 ]; then
        echo "Tessera is taking a long time to start.  Look at the Tessera logs in qdata/logs/ for help diagnosing the problem."
    fi
    echo "Waiting until all Tessera nodes are running..."

    sleep 5
done

echo "All Tessera nodes started"
exit 0

**Comment by matrixoneken** [comment]
I can see the running command is as following

**java   -Xms128M -Xmx128M -cp /home/vagrant/tessera/mysql.jar -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c1/tessera-config1.json >> qdata/logs/tessera1.log 2>&1 &**

But I get the error in the log file as following and can not start the tessera node

 Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'org.h2.Driver' for connect URL 'jdbc:mysql//127.0.0.1:3306/quorum?useSSL=false'
Error Code: 0
	at org.glassfish.grizzly.servlet.WebappContext.initServlets(WebappContext.java:1920) ~[tessera.jar:na]
	at org.glassfish.grizzly.servlet.WebappContext.deploy(WebappContext.java:345) ~[tessera.jar:na]
	at com.quorum.tessera.server.JerseyServer.start(JerseyServer.java:111) [tessera.jar:na]
	at com.quorum.tessera.Launcher.runWebServer(Launcher.java:107) [tessera.jar:na]
	at com.quorum.tessera.Launcher.main(Launcher.java:52) [tessera.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [tessera-spring.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'org.h2.Driver' for connect URL 'jdbc:mysql//127.0.0.1:3306/quorum?useSSL=false'
Error Code: 0


How to add mysql to 7nodes?

**Comment by prd-fox** [comment]
Ah, I think the issue is that the change was made after the last release.
Can you try building Tessera from master instead of using the v0.6?

Additionally, the class path hasn't been setup correctly for using an external database driver.
The command should be:
```
java -Xms128M -Xmx128M -cp /home/vagrant/tessera/mysql.jar:/home/vagrant/tessera/tessera.jar com.quorum.tessera.Launcher -configfile qdata/c1/tessera-config1.json >> qdata/logs/tessera1.log 2>&1 &
```

Also, there is a small typo in the JDBC URL; you are missing a colon after 'mysql'

**Comment by matrixoneken** [comment]
Thank you for your answer.
I have cloned the branch master and build with  mvn package -Dmaven.test.skip=true

I get the error as following:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.022 s
[INFO] Finished at: 2018-09-19T17:39:06+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.1:check (check) on project config: Coverage checks have not been met. See log for details. -> [Help 1]

**Comment by matrixoneken** [comment]
Can you release the jar file of the new version? Thank you.

**Comment by prd-fox** [comment]
Can you run
```
mvn clean package -Dmaven.test.skip=true
```
or
```
mvn clean package -DskipTests=true
```
The coverage issue stems from a previously failed build. Cleaning the project first will allow the coverage checks to not be executed.

**Comment by matrixoneken** [comment]
I have packaged from branch matser by myself. And changed the command as following:
java   -Xms128M -Xmx128M -cp /home/vagrant/tessera/mysql.jar:/home/vagrant/tessera/tessera.jar com.quorum.tessera.Launcher -configfile qdata/c1/tessera-config1.json >> qdata/logs/tessera1.log 2>&1 &

I  get the error as before.

org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'org.h2.Driver' for connect URL 'jdbc:mysql//127.0.0.1:3306/quorum?useSSL=false'
Error Code: 0

My jar file about mysql jdbc is downloaded from 
https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java_8.0.12-1ubuntu16.04_all.deb

**Comment by namtruong** [comment]
@matrixoneken it looks like you're missing a colon in your jdbc url - it should be jdbc:mysql://127.0.0.1:3306/....

**Comment by matrixoneken** [comment]
@namtruong  thank you for your answer. I have add a colon and also get the error as following:

org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'org.h2.Driver' for connect URL '**jdbc:mysql://127.0.0.1:3306/quorum?useSSL=false**'
Error Code: 0
12:22:37.364 [main] ERROR eclipselink.logging.ejb - Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'org.h2.Driver' for connect URL 'jdbc:mysql://127.0.0.1:3306/quorum?useSSL=false'
Error Code: 0
12:22:37.366 [main] WARN  o.s.c.s.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [tessera-spring.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'org.h2.Driver' for connect URL 'jdbc:mysql://127.0.0.1:3306/quorum?useSSL=false'
Error Code: 0
12:22:37.385 [main] ERROR o.g.grizzly.servlet.WebappContext - [WebappContext] Exception deploying application.  See stack trace for details.
java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [tessera-spring.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class 'org.h2.Driver' for connect URL 'jdbc:mysql://127.0.0.1:3306/quorum?useSSL=false'
Error Code: 0
	at org.glassfish.grizzly.servlet.WebappContext.initServlets(WebappContext.java:1920) ~[tessera.jar:na]
	at org.glassfish.grizzly.servlet.WebappContext.deploy(WebappContext.java:345) ~[tessera.jar:na]
	at com.quorum.tessera.server.JerseyServer.start(JerseyServer.java:111) [tessera.jar:na]
	at com.quorum.tessera.Launcher.runWebServer(Launcher.java:107) [tessera.jar:na]
	at com.quorum.tessera.Launcher.main(Launcher.java:52) [tessera.jar:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [tessera-spring.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.1.v20171221-bd47e8f): org.eclipse.persistence.exceptions.DatabaseException

**Comment by prd-fox** [comment]
Are you sure you are running with the freshly built jar?
It looks like you are still using the old jar file (v0.6), which has the 'org.h2.Driver' as the default choice, which is no longer the case.

In the command I gave you before which specified the class path:
```
-cp /home/vagrant/tessera/mysql.jar:/home/vagrant/tessera/tessera.jar
```
the second jar is the Tessera one. Did you overwrite the jar file with the freshly compiled one? Otherwise you will still be using the old jar.

**Comment by matrixoneken** [comment]
I have overwrited the jar file with the freshly compiled one. I can find the following content in swagger.html in jar file. 

Tessera rest
HTTP | HTTPS://localhost:8080/

Version 0.7-SNAPSHOT

but in old version I only find version-0.6 and it is not 0.7.

**Comment by matrixoneken** [comment]
I have overwrite the jar file with the freshly compiled one. I can find the following content in swagger.html 

Tessera rest
HTTP | HTTPS://localhost:8080/

Version 0.7-SNAPSHOT

**Comment by matrixoneken** [comment]
I have overwrite the jar file with the freshly compiled one. I can find the following content in swagger.html 

Tessera rest
HTTP | HTTPS://localhost:8080/

Version 0.7-SNAPSHOT

**Comment by Krish1979** [comment]
please reopen if it is still an issue
