### ISSUE TITLE
Create enclave deployment artefact

### ISSUE THREAD

**Issue by melowe** [Consensys-Incorporated/tessera#488]
The encryption-api module defines enclave as the service that core uses for encryption operations and key access. Private keys should never be exposed outside of its system boundary. 

One of the proposed deployment options is that enclave can be co-deployed in the same location as private keys and expose its services to tessera which is potentially deployed in a different location. 

Task 1. Provide optional enclave api/transport options to communicate with tessera core. 
Task 2. Provide optional configuration that instructs tessera core how to access enclave securely.

**Comment by melowe** [comment]
Related #512

**Comment by prd-fox** [comment]
See related issue.
