### ISSUE TITLE
Azure support too try coupled to core application

### ISSUE THREAD

**Issue by melowe** [Consensys-Incorporated/tessera#506]
The azure key vault support is too tightly coupled to the core. We need to position the code so we can create key vault specific deployments or even allow users to bootstrap key vaults at runtime. 

1. The azure module needs to provide a spring config that is boot strapped like other modules
2. Some adaptor/provider object needs to be added to the key vault module that looks up the implementation via the service loader (this will help address the instanceof checks in the convertor)
3. Create über jar for the azure module that includes its dependencies, that can be added to the class path during startup and/or can be included in an azure profile build.

**Comment by chris-j-h** [comment]
Completed in [PR 538](https://github.com/jpmorganchase/tessera/pull/538)
