### ISSUE TITLE
Does anyone know how to connect mysql?

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/tessera#507]
Following url is my issue
https://github.com/jpmorganchase/tessera/issues/465

Does anyone know how to connect mysql? Thank you!

**Comment by prd-fox** [comment]
Hey.

As explained in the other issue, once you have built the master branch of Tessera, then it just a case that you set the JDBC URL correctly in the configuration.

A release of the next version shouldn't be far away if you are willing to wait and don't want to build it yourself.

**Comment by matrixoneken** [comment]
I have built the source code with 'mvn package' and got the 0.7 version in tessera-core project. I replaced the 0.6 version.  But I can not run the 7nodes example. I got the following error in log.
no main manifest attribute in /root/vagrant/tessera/tessera.jar

I wanth to konw which project I can get the new version?

**Comment by Krish1979** [comment]
The new release is now available (Tessera 0.7) which has the jdbc configuration for mysql. Please try and confirm back

**Comment by matrixoneken** [comment]
I have try the 0.7 version and get following error:

 Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL 'jdbc:mysql://localhost:3306/quorum'
Error Code: 0
05:12:07.455 [main] ERROR eclipselink.logging.ejb - Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL 'jdbc:mysql://localhost:3306/quorum'
Error Code: 0
05:12:07.456 [main] WARN  o.s.c.s.ClassPathXmlApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [tessera-core-spring.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL 'jdbc:mysql://localhost:3306/quorum'
Error Code: 0
Error creating bean with name 'entityManagerFactory' defined in class path resource [tessera-core-spring.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.apache.commons.dbcp.SQLNestedException: Cannot create JDBC driver of class '' for connect URL 'jdbc:mysql://localhost:3306/quorum'
Error Code: 0


I can see the following command:
**java -Xms128M -Xmx128M -cp /root/vagrant/tessera/mysql.jar -jar /home/vagrant/tessera/tessera.jar -configfile qdata/c1/tessera-config1.json >> qdata/logs/tessera1.log 2>&1 &**

And mysql version is 5.7.24. I also confirm the path of mysql.jar  is right because I can wirte a java program to connect the mysql with the mysql.jar

Please tell me how to do. thank you.

**Comment by melowe** [comment]
When bootstrapping the jdbc driver you need to add both the jdbc driver jar and the tessera jar 

```
java -cp some-jdbc-driver.jar:/path/to/tessera-app.jar:. com.quorum.tessera.Launcher
```

Please try something like below (i used your parameters). 

```
java -Xms128M -Xmx128M -cp /root/vagrant/tessera/mysql.jar:/home/vagrant/tessera/tessera.jar -com.quorum.tessera.Launcher configfile qdata/c1/tessera-config1.json >> qdata/logs/tessera1.log 2>&1 &
```

**Comment by matrixoneken** [comment]
java   -Xms128M -Xmx128M -cp /root/vagrant/tessera/mysql.jar -jar:/home/vagrant/tessera/tessera.jar -com.quorum.tessera.Launcher -configfile qdata/c7/tessera-config7.json >> qdata/logs/tessera7.log 2>&1 &

I used above  command and I got following error
Unrecognized option: -jar:/home/vagrant/tessera/tessera.jar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


Please tell me how to do. thank you.

**Comment by matrixoneken** [comment]
The path of mysql.jar is  /root/vagrant/tessera/mysql.jar 
The path of tessear.jar is  /home/vagrant/tessera/tessera.jar

Please tell me how to write the command. thank you.

**Comment by melowe** [comment]
My apologies I think I had a typo.. it should be something like 
```
java -Xms128M -Xmx128M -cp /root/vagrant/tessera/mysql.jar:/home/vagrant/tessera/tessera.jar:. com.quorum.tessera.Launcher -configfile qdata/c1/tessera-config1.json >> qdata/logs/tessera1.log 2>&1 &
```

**Comment by namtruong** [comment]
Hi, as per our readme doc, please use the below command 
java -Xms128M -Xmx128M -cp /root/vagrant/tessera/mysql.jar:/home/vagrant/tessera/tessera.jar:. com.quorum.tessera.Launcher -configfile qdata/c1/tessera-config1.json >> qdata/logs/tessera1.log 2>&1 &

Please note -cp and -jar cannot be used together

**Comment by matrixoneken** [comment]
Now I can connect to the mysql. Thank you!
But when I use js to deploy a smart contract and set a privatefor key , I get following error:


could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '\x7F\x9E\x86x\xB5\xE8{\xA3\xDD\x91j\x9C\xB2\x0C\xAA\xDC\xBBG\xEB' for key 'PRIMARY'
Error Code: 1062
Call: INSERT INTO ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD, TIMESTAMP, HASH) VALUES (?, ?, ?)
	bind => [3 parameters bound]

And if I deployed a smart contract without privatefor key, everything is OK

Please tell me how to deploy smart contract in 7nodes example with mysql. Thank you.

**Comment by namtruong** [comment]
The error message above indicates that you're inserting a duplicate entry into the database. This might as well just be a re-send attempt. Also the hash (primary key) above doesn't look to be in the correct format.

In order for us to diagnose this further please could you please send the complete log and also steps to reproduce the issue.

Many thanks

**Comment by matrixoneken** [comment]
[tessera1.log](https://github.com/jpmorganchase/tessera/files/2587672/tessera1.log)
[tessera2.log](https://github.com/jpmorganchase/tessera/files/2587674/tessera2.log)
[tessera3.log](https://github.com/jpmorganchase/tessera/files/2587677/tessera3.log)
[tessera4.log](https://github.com/jpmorganchase/tessera/files/2587678/tessera4.log)
[tessera5.log](https://github.com/jpmorganchase/tessera/files/2587679/tessera5.log)
[tessera6.log](https://github.com/jpmorganchase/tessera/files/2587681/tessera6.log)
[tessera7.log](https://github.com/jpmorganchase/tessera/files/2587683/tessera7.log)
[1.log](https://github.com/jpmorganchase/tessera/files/2587684/1.log)
[2.log](https://github.com/jpmorganchase/tessera/files/2587686/2.log)
[3.log](https://github.com/jpmorganchase/tessera/files/2587687/3.log)
[4.log](https://github.com/jpmorganchase/tessera/files/2587688/4.log)
[5.log](https://github.com/jpmorganchase/tessera/files/2587689/5.log)
[6.log](https://github.com/jpmorganchase/tessera/files/2587690/6.log)
[7.log](https://github.com/jpmorganchase/tessera/files/2587691/7.log)

The complete log I have uploaded. After running 'sh raft-start.sh tessera.', I ran './runscript.sh private-contract.js' and got following error:

err creating contract Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Length:[659] Connection:[keep-alive] Content-Type:[text/plain]] Body:0xc435598f40 ContentLength:659 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc435818700 TLS:<nil>}

**It was the first time that I ran './runscript.sh private-contract.js' and the table was empty before my running.**

When I found the tessera1.log ,I got  following error which you could find in  tessera1.log


org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '\x80\xEE,!{]\x12qg-|\x0F\xBB\x01N\xF6,j\xC0\x19\x80\xEB\x8Bo`\xB' for key 'PRIMARY'
Error Code: 1062
Call: INSERT INTO ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD, TIMESTAMP, HASH) VALUES (?, ?, ?)
	bind => [3 parameters bound]
Query: InsertObjectQuery(com.quorum.tessera.transaction.model.EncryptedTransaction@2c5c36c9)
20:53:17.708 [jersey-server-managed-async-executor-2] ERROR c.q.t.a.e.DefaultExceptionMapper - Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '\x80\xEE,!{]\x12qg-|\x0F\xBB\x01N\xF6,j\xC0\x19\x80\xEB\x8Bo`\xB' for key 'PRIMARY'
Error Code: 1062
Call: INSERT INTO ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD, TIMESTAMP, HASH) VALUES (?, ?, ?)
	bind => [3 parameters bound]
Query: InsertObjectQuery(com.quorum.tessera.transaction.model.EncryptedTransaction@2c5c36c9)
20:53:17.709 [jersey-server-managed-async-executor-2] INFO  c.q.tessera.api.filter.LoggingFilter - Exit Request : POST : /sendraw
20:53:17.709 [jersey-server-managed-async-executor-2] INFO  c.q.tessera.api.filter.LoggingFilter - Response for sendraw : 500 Internal Server Error

**Comment by matrixoneken** [comment]
![image](https://user-images.githubusercontent.com/41671830/48593727-02b4e100-e989-11e8-9889-86198e346b37.png)

The table in mysql is like above image

**Comment by namtruong** [comment]
@matrixoneken thanks for the above - just to confirm by the look of it - do you have all 7 nodes connecting to the same mysql database? 
Each node when processing and storing transaction will generate the same hash as primary key - and if they're trying to persist to one database then it will throw exceptions with duplicate transaction.

They will need to have separate databases for each

**Comment by Krish1979** [comment]
each Tessera node needs to have its own DB
