### ISSUE TITLE
Enclave as distinct service

### ISSUE THREAD

**Issue by melowe** [Consensys-Incorporated/tessera#512]
Enclave needs to be runnable as a distinct service that can optionally be deployed separately to the transaction manager. The architectural assuming being that access to private keys is only available within the system boundaries of the enclave. 

1. Add server config for enclave
2. Create standalone enclave jar that can be deployed externally from the core tessera application

┆Issue is synchronized with this [Trello card](https://trello.com/c/Zk5D3X16)

**Comment by vietlq** [comment]
Do you have any specific enclave in mind to be used? Yubi HSM2 has some nice features and is pretty cheap https://www.yubico.com/product/yubihsm-2/ . I can see that Enclave interface is nicely designed and can accommodate various implementations to different back-ends: https://github.com/jpmorganchase/tessera/blob/8c0bad8867b6e126116de27be946e202ca10ebdb/encryption/encryption-api/src/main/java/com/quorum/tessera/encryption/Enclave.java

**Comment by melowe** [comment]
https://github.com/jpmorganchase/tessera/pull/623

Adds most plumbing code for proxying enclave invocations behind a Websocket. Using a stateful protocol will allow us to add run status functions to enclave so the status can be checked before attempting process transactions. 

Outstanding items 
1. Add enclave factory that when reading configuration will create an Enclave client. 
2. Test and address any performance enhancements. 
3. Create thread that can test enclave's runtime status and attempt to start as a given interval (required for enclave-jaxrs and enclave-websockets)
4. Add minimal cli to start enclave-websockets 
5. Add relevant suites and/or tags to fire up remote enclave instances and ensure tests pass as usual.
