### ISSUE TITLE
Support multiple key management vault integration

### ISSUE THREAD

**Issue by Krish1979** [Consensys-Incorporated/tessera#517]
Microsoft Azure support was our test & trail implementation for external key management but it is too closely coupled with core application. We should decouple (#506) and refactor to make it easier to integrate and support out key management vaults like AWS, Hashicorp Vault etc.

**Comment by prd-fox** [comment]
Hashicorp has done a fair amount of refactoring on this front, and has been merged. Any future vaults which need refactoring will have it done as part of their ticket.
