### ISSUE TITLE
Unit test fail in AzureVaultKeyGeneratorTest when build with linux file system

### ISSUE THREAD

**Issue by namtruong** [Consensys-Incorporated/tessera#525]
This unit test exceptionThrownIfDisallowedCharactersUsedInVaultId expects java.nio.charset.UnsupportedCharsetException to be thrown however before that, Paths.get(filename) would attempt to use FileSystems.getDefault() to validate the file path, and this might return different outcomes depending on the OS system Tessera is being built in. In OS such as linux this method in Paths library will throw a different exception (java.nio.file.InvalidPathException) - causing the unit test to fail

**Comment by namtruong** [comment]
Fixed by #527

**Comment by Krish1979** [comment]
Fixed in 0.7.3 release
