### ISSUE TITLE
Resend poller not differentiating between URL's with trailing slash (causing infinite 'resend' requests)

### ISSUE THREAD

**Issue by SatpalSandhu61** [Consensys-Incorporated/tessera#529]
The resend poller isn't differentiating between "http://localhost:9001" and "http://localhost:9001/" (with the trailing slash that was added for constellation).
In the event that auto-discovery is disabled, then this has the impact of causing a "resend" request every 2 seconds (ad-infinitum).

**To reproduce:**
- Set up two nodes, with both configured as peers:
```
    "peer": [ {"url": "http://localhost:9001" }, {"url": "http://localhost:9002"} ],
```
- On node 1, disable auto-discovery:
```
    "disablePeerDiscovery": true,
```
- Start up both nodes.
- On examination of the logs on node 2, you will observe the following every 2 seconds: "Enter Request : POST : /resend"

**Temporary workaround:**
- Add a backslash to the peer url's in the config, e.g.:
```
    "peer": [ {"url": "http://localhost:9001/" }, {"url": "http://localhost:9002/"} ],
```

**Comment by melowe** [comment]
When reading config and testing if a given party is in the party info node, we use string testing. This means that a url with a trailing slash is different to one without. This means if a user doesn't use a trailing space the presence of a given party won't be detected.

Action
Check hash codes and equals in party to compare equality is a less error prone way.

**Comment by prd-fox** [comment]
Although the resend poller doesn't differentiate, it no longer causes an infinite loop, as as such the main issue is fixed.
