### ISSUE TITLE
How to deplopy a privatefor contract with tessera which connecting to the mysql

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/tessera#533]
var Web3 = require('web3')
var web3 = new Web3(new Web3.providers.HttpProvider('http://192.168.193.64:22000')) //node1 rpc address
var version = web3.version.node;
console.log("version:"+version);
var mainAbi=[{"constant":false,"inputs":[{"name":"strVal","type":"string"}],"name":"Set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"Get","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"holdings","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"strVal","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}];
var mainBytecode ="0x608060405234801561001057600080fd5b50604051610514380380610514833981018060405281019080805182019291905050508060009080519060200190610049929190610050565b50506100f5565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061009157805160ff19168380011785556100bf565b828001600101855582156100bf579182015b828111156100be5782518255916020019190600101906100a3565b5b5090506100cc91906100d0565b5090565b6100f291905b808211156100ee5760008160009055506001016100d6565b5090565b90565b610410806101046000396000f300608060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806334541fcd1461005c578063b1976a02146100c5578063e79bf13b14610155575b600080fd5b34801561006857600080fd5b506100c3600480360381019080803590602001908201803590602001908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505091929192905050506101e5565b005b3480156100d157600080fd5b506100da6101ff565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561011a5780820151818401526020810190506100ff565b50505050905090810190601f1680156101475780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34801561016157600080fd5b5061016a6102a1565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156101aa57808201518184015260208101905061018f565b50505050905090810190601f1680156101d75780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b80600090805190602001906101fb92919061033f565b5050565b606060008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102975780601f1061026c57610100808354040283529160200191610297565b820191906000526020600020905b81548152906001019060200180831161027a57829003601f168201915b5050505050905090565b60008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156103375780601f1061030c57610100808354040283529160200191610337565b820191906000526020600020905b81548152906001019060200180831161031a57829003601f168201915b505050505081565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061038057805160ff19168380011785556103ae565b828001600101855582156103ae579182015b828111156103ad578251825591602001919060010190610392565b5b5090506103bb91906103bf565b5090565b6103e191905b808211156103dd5760008160009055506001016103c5565b5090565b905600a165627a7a723058204e0f342b1d9b9db66f0d458a7d24ac3a066a5919d1c5c3011f4453a5f78dfb6e0029";
var maincontractContract = web3.eth.contract(mainAbi);
var coinbase = web3.eth.accounts[0];
console.log("coinbase:"+coinbase);

var strVal="BTC-10,ETH-10"
var maincontract = maincontractContract.new(
    strVal,
    {
        from: coinbase,
        data: mainBytecode,
        gas: '0x47b760',
        privateFor: ["QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="]  //set contract private for node2
    }, function (e, contract) {
        // console.log(e, contract);
        try {

            if (typeof contract.address !== 'undefined') {
                console.log('Main Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);

           }
            else {
                if (e != null) {

                    console.log('Main Contract mined error'+ e.toString());

                }

            }
        }catch(e)
        {
            console.log('Main Contract mined error'+ e.toString());
        }
    });

Above js code is deploying a privatefor contract to quorum with tessera. When the tessera is connecting to the H2, everything is ok. But when the tessear is connecting to the  mysql , the program can not get the contract address and be waiting for a long time.

When I checked the log I found following information

RACE[11-19|21:47:12] Rejected peer before protocol handshake  id=ac6b1096ca56b9f6 addr=127.0.0.1:21000 conn=staticdial err="connected to self"
TRACE[11-19|21:47:12] Dial task done                           task="staticdial ac6b1096ca56b9f6 127.0.0.1:21000"
TRACE[11-19|21:47:12] New dial task                            task="wait for dial hist expire (29.999998116s)"

Can someone tell me how to deploy a privatefor contract with web3 and mysql? Thank you.

**Comment by matrixoneken** [comment]
[TestProject.zip](https://github.com/jpmorganchase/tessera/files/2597860/TestProject.zip)
I upload my code. it can be run by node.js .

**Comment by prd-fox** [comment]
If the application works fine with the default H2 database, then it should not be an error with the web3 application.

I set up a MySQL server fresh and had the following schema:
`CREATE TABLE ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD BLOB NOT NULL, HASH VARBINARY(100) NOT NULL, TIMESTAMP BIGINT, PRIMARY KEY (HASH));`

The connection string I put in the configuration file was:
`"url": "jdbc:mysql://127.0.0.1:3306/mydatabase"`

I created the database "mydatabase" and the ENCRYPTED_TRANSACTION table (using the SQL provided) before running the application.

Lastly, the java command used was:
`java -cp /home/vagrant/mysql-connector-java-8.0.13.jar:/home/vagrant/tessera/tessera.jar com.quorum.tessera.Launcher -configfile qdata/c1/tessera-config1.json`

This had no issue sending through transactions and them being processed correctly. Can you please post your connection string and any errors found in the tessera logs? The errors you posted are from the Quorum logs and won't give an indication of any errors that may be happening at the database level.

Thanks

**Comment by prd-fox** [comment]
Also, looking at the past issues you raised about this, it is important to note that:

1) Each node must have its own database (you can use the same database server, but each must use its own database).
2) It is normal to see constraint violations when restarting a node in an existing network.

**Comment by matrixoneken** [comment]
[1.log](https://github.com/jpmorganchase/tessera/files/2602197/1.log)
[2.log](https://github.com/jpmorganchase/tessera/files/2602198/2.log)
[3.log](https://github.com/jpmorganchase/tessera/files/2602199/3.log)
[4.log](https://github.com/jpmorganchase/tessera/files/2602200/4.log)

[5.log](https://github.com/jpmorganchase/tessera/files/2602203/5.log)
[6.log](https://github.com/jpmorganchase/tessera/files/2602204/6.log)
[7.log](https://github.com/jpmorganchase/tessera/files/2602205/7.log)
[tessera1.log](https://github.com/jpmorganchase/tessera/files/2602206/tessera1.log)
[tessera2.log](https://github.com/jpmorganchase/tessera/files/2602207/tessera2.log)
[tessera3.log](https://github.com/jpmorganchase/tessera/files/2602209/tessera3.log)
[tessera4.log](https://github.com/jpmorganchase/tessera/files/2602210/tessera4.log)
[tessera5.log](https://github.com/jpmorganchase/tessera/files/2602211/tessera5.log)
[tessera6.log](https://github.com/jpmorganchase/tessera/files/2602212/tessera6.log)
[tessera7.log](https://github.com/jpmorganchase/tessera/files/2602213/tessera7.log)

The whole log I have uploaded. I run 7 nodes example and I have build 7 db for each node. I can see the record about transaction like following images but the contract can not be mined and can not get the contract address

![image](https://user-images.githubusercontent.com/41671830/48812676-86f8c280-ed01-11e8-9998-858730d56ef8.png)
![image](https://user-images.githubusercontent.com/41671830/48812682-937d1b00-ed01-11e8-9876-73e4239603ad.png)

**Comment by prd-fox** [comment]
The logs all indicate that everything is fine. Tessera shared the transactions, the transaction made its way into a block and all nodes processed the block.

I copied the setup you have above and ran the "DeployMainContract.js" and "GetMainContract.js" files, and nodes 1 and 2 had the output "合约内容：BTC-10,ETH-10" with node 7 giving an error (since it didn't have the correct information).

Are these the correct files to be using?

I'm struggling to find an issue with the setup.

**Comment by matrixoneken** [comment]
DeployMainContract.js  is deploying a private contract. If you can get the contract address, it means everything is ok.

GetMainContract.j is getting content about the private contract from the address which got by DeployMainContract.js. The content is "合约内容：BTC-10,ETH-10" , so you are right.

But I can not get the contract address and the program is always running. Please see following image
![image](https://user-images.githubusercontent.com/41671830/48892598-66537880-ee79-11e8-9eb2-fcd3574d6120.png)

I want to know why I can not get the contract address. Thank you

**Comment by prd-fox** [comment]
I managed to reproduce the problem now.
Note that this also happens with H2, and is not to do with Tessera, so your MySQL setup is correct and working properly.

This seems to be about using raft based consensus. The block is minted too quickly, and so the callback function likely isn't set in the web3js app before the transaction is mined, meaning the callback is never fired.

A couple of workarounds:

1. Consider adding a longer raft block creation time using the instructions [here](
https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md#minting-frequency). This will only work in a constantly active network, and will only mitigate the issue, not solve it.
2. Send another transaction in. Creating another block causes the callback of the hung transaction to be fired. Obvious drawback is you may not want to send in another transaction.
3. Consider upgrading to the 1.0 version of web3js. It is still in beta, but has support for promise-style callbacks, which I think will help with this issue.

**Comment by Krish1979** [comment]
this issue is not to do with Tessera, hence closing issue.
