### ISSUE TITLE
Decrypting locked key without password gives wrong error message

### ISSUE THREAD

**Issue by prd-fox** [Consensys-Incorporated/tessera#541]
When decrypting a locked key, the default password of "" is used to denote that a password is not present for this key.

This empty string is then used to actually decrypt the key, and the resulting error message is that it was the wrong password.
The correct error message should state that no password was provided.

**Comment by vietlq** [comment]
Empty password is actually a valid input for key defivation/key stretching function (Argon2):

https://github.com/jpmorganchase/tessera/blob/e41d15b6459e219095a202af76d9435b922b48df/config/src/main/java/com/quorum/tessera/config/keys/KeyEncryptorImpl.java#L106

If this error is implemented, it will disallow cases where users wish to have empty passwords. So *wrong password* is rather correct for the cases when empty string is not the correct password.

**Comment by prd-fox** [comment]
The user is not able to generate a key with an empty password. If an empty password is provided then it will generate an unlocked key.
The user has no path through the system to generate a locked key with an empty password (unless they manually do the same steps using another tool).
