### ISSUE TITLE
Upcheck works even when database tables aren't setup correctly

### ISSUE THREAD

**Issue by melowe** [Consensys-Incorporated/tessera#552]
Upcheck and other rest calls return ok status regardless of database state. For an upcheck to be successful some validation of the DB state should happen and an appropriate error status returned so fail early rather than when attempting to access data. 

Action: Add validation query to relevant status check endpoints e.g. select count(*) from table name or something similar.

**Comment by Krish1979** [comment]
include the public keys of the Tessera node on the response too..
