### ISSUE TITLE
Column TIMESTAMP missing on H2 migration

### ISSUE THREAD

**Issue by dhyansraj** [Consensys-Incorporated/tessera#573]
After datadir migration to H2, getting following error

![image](https://user-images.githubusercontent.com/22983630/50111246-56298180-020a-11e9-9e87-cc270135d39e.png)

I was able to fix this by manually adding a column TIMESTAMP(DECIMAL).

![image](https://user-images.githubusercontent.com/22983630/50111288-7b1df480-020a-11e9-89ef-8bf361bbb2ea.png)

Can you please confirm this issue, I can create a pull request if so.

**Comment by SatpalSandhu61** [comment]
The timestamp was added in v0.7, so it looks like it was missed from the exporter.
If you can create a PR then that would be very helpful.
If you haven't already completed a [CLA ](https://github.com/jpmorganchase/cla/), then can you also do that pls?
Many thanks.

**Comment by melowe** [comment]
We've already added a more generalised JDBC database exporter allowing users define a properties file with the insertRow and createTable queries and the url . There is a snapshot available: 

https://github.com/jpmorganchase/tessera/blob/snapshots/com/quorum/tessera/data-migration/0.8-SNAPSHOT/data-migration-0.8-20181128.172230-1.jar

Using the snapshot version with the following options could resolve the problem.

Ideally code fixes for the H2Exporter should be to replace it with the JDBC exporter with the export type and dbconfig file taken care of. 

Workaround with snapshot jar requires exporttype and dbconfig options. 
`-exporttype JDBC -dbconfig /somefile.properties`

somefile.properties
```
insertRow=insert stuff
createTable=create stuff
jdbcUrl=jdbc:bla
```
