### ISSUE TITLE
url mandatory for node

### ISSUE THREAD

**Issue by dhyansraj** [Consensys-Incorporated/tessera#577]
othernodeurl was optional in Constellation, while the equivalent 'url' property is mandatory in Tessera. We are trying to add Tessera support in Quorum Maker, which allows creating a quorum network by adding nodes one by one. At the time of first node creation, there are no other nodes to connect and this worked perfectly since othernodeurl was optional in Constellation. Is there a way to make this optional ?

**Comment by SatpalSandhu61** [comment]
@dhyansraj you're quite right, currently as least one peer url must be specified. We'll take a look and see whether we can make that optional.
In the meantime, a workaround that you can use for creating the first node is to set up a single peer url which connects to the first node itself. I've tried this out and it seems to work without any adverse impact.

I'll close this ticket and create one on our backlog for making the url optional.
