### ISSUE TITLE
Resend should also restore missing transactions for an originating node

### ISSUE THREAD

**Issue by SatpalSandhu61** [Consensys-Incorporated/tessera#579]
Currently, if a node loses its database then transactions are restored by means of the other nodes performing a resend for transactions where it is a participant.
However, if the failed node is the originator of the transaction, then those transactions won't be restored. See issue # [607](https://github.com/jpmorganchase/quorum/issues/607).
This represents a flaw in the restore mechanism and means that users would have to build their own mechanism to store transactions and restore them after a node failure.

We should therefore extend the resend so that transactions are also restored to the originating node.

Note that Tessera stores the sender of a transaction, so that could be used in order to restore transactions back to the originating node.

**Comment by prd-fox** [comment]
Using last comment above as a starting point, the solution would be:

1. Resend the tx from a receiving node back to the originator (using a new endpoint to identify the nature of this resend, maybe?)
2. Recreate the tx in the originating node as if it has no participants
3. Add the recipient that sent us this as one of the recipients
4. If another node sends us the same tx, add it as a recipient too, so we can rebuild the list of participants.

Note that if note that if both the originator AND a recipient both lose the data, then it becomes a lot harder to recover this, and will not be included in the scope of this issue. It would require some verification that the recipient was indeed an original party (probably using some data on the blockchain).
