### ISSUE TITLE
Update /config/peers as part of node to node interaction

### ISSUE THREAD

**Issue by melowe** [Consensys-Incorporated/tessera#583]
`/config/peers ` we only added as a means for verifying add peer invocations made by the admin cli. While this verification should be distinct as an admin service, however providing a read only path to list all the peers in a current network (including those added during party info dialogues) is desirable.

**Comment by prd-fox** [comment]
Adding some extra parameters that display the "last connected" time, and number of failed requests to the target. The aim is to give the user some extra context to determine if the peer is offline or not.
