### ISSUE TITLE
Http Get /partyinfo URL “HTTP 405 Method Not Allowed”

### ISSUE THREAD

**Issue by a651694192** [Consensys-Incorporated/tessera#615]
Be sure node itself runs well, but get /partyinfo return this error.
command is :   curl http://localhost:9001/partyinfo

**Comment by prd-fox** [comment]
Which version of Tessera are you using?
The endpoint has both GET and POST methods, with the GET method only being available in 0.8, so I would expect to see this if you are running version 0.7.3 or earlier.

**Comment by Krish1979** [comment]
please update to latest jar and reopen ticket if it is still an issue
