### ISSUE TITLE
Address assignment issue for P2P

### ISSUE THREAD

**Issue by harshal619** [Consensys-Incorporated/tessera#622]
Hello,

I am trying to build Quorum network between two server's using tessera.
First system is directly exposed to internet on which i have hosted first node including tessera node.

Second system is running on VM which is accessed using jump server.

While starting node i had to put 127.0.0.1 (localhost) address on this second system.
This works well for Geth node. Both nodes are connected an synchronizing.

But i am facing an issue while starting tessera node on second system.
If i put local host on P2P configuration in tessera, node start fine but first tessera node throws an error saying:
Connection refused (Connection refused) when connecting to http://127.0.0.1:9003

Which is obvious.

I tried putting second server's IP on which VM is running in tessera config as well.
At the time of starting node with external IP i get following error:
c.quorum.tessera.server.JerseyServer - Starting http://<external ip>:9003
Cannot assign requested address

This seems like chicken and egg situation to me.

BR,
Harshal

**Comment by prd-fox** [comment]
Can you share the config file for both nodes? Specifically the server settings and peers list?

**Comment by harshal619** [comment]
Hi @prd-fox 

Attaching my server config files for both nodes.

[server-configs.zip](https://github.com/jpmorganchase/tessera/files/2836163/server-configs.zip)

BR,
Harshal

**Comment by prd-fox** [comment]
Thanks. The configs looks mostly okay to me. 

You say you are running in a VM, are you assigning the public IP of the the host machine or the VM? It looks like you are doing the host machine, but then you use the `bindingAddress` to be the host machine too - this should be the VMs internal IP which the host forwards requests to (and it should also contains the port number).

Can you edit the `bindingAddress` and try again? Let me know if you need more explanation.

**Comment by harshal619** [comment]
Hi,

Tried putting 0.0.0.0 as binding Address and used public IP of host machine as hostName and it worked fine.
Thanks for your help.

BR,
Harshal

**Comment by prd-fox** [comment]
No problem, glad it's sorted!
