### ISSUE TITLE
Tessera Cross Origin Issues while calling the rest API ( /storeraw )

### ISSUE THREAD

**Issue by muthu-param** [Consensys-Incorporated/tessera#709]
We are using tessera for execute private transaction's in Quorum. When invoking the third party (privateURL) API from the postman, we are getting expected output. but when we are calling the same API's from the another server we getting empty response with 200 status code( http://:9081/storeraw). This issue is happening due to the CORS. we checked with File:/// it's working.

How to enable CORS for tessera third party API's?

**Comment by jiten-balla** [comment]
@fixanoid Can you please help us on this issue.

**Comment by nicolae-leonte-go** [comment]
Setting CORS is not possible right now in Tessera. We'll add it to the backlog and let you know as soon as it is available.

For now please consider proxying the call via your server.

**Comment by nicolae-leonte-go** [comment]
Alternatively if you are able to check out and rebuild tessera locally you can also try to add the response headers you need in com.quorum.tessera.thridparty.RawTransactionResource line 54:

Ex: 
        return Response.status(Status.OK)
                .type(APPLICATION_JSON)
                .header("Access-Control-Allow-Origin", "*")
                .entity(response)
                .build();

The tessera fix will most likely be similar to the geth --rpccorsdomain option but we may need a few days to implement that.

**Comment by nicolae-leonte-go** [comment]
A CORS fix has been merged to master. You can get the latest docker image (snapshot build) using:
docker pull quorumengineering/tessera:latest

We intend to add configuration for the CORS domains - which will come in a later pull request.
