### ISSUE TITLE
mvn install failure

### ISSUE THREAD

**Issue by ylfly** [Consensys-Incorporated/tessera#730]
When running the _mvn install_ command, a failure in project **config** occurs as follows:
[ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.182 s <<< FAILURE! - in com.quorum.tessera.config.JaxbConfigFactoryTest
[ERROR] cantAppendToPasswordFileThrowsError(com.quorum.tessera.config.JaxbConfigFactoryTest)  Time elapsed: 0.035 s  <<< FAILURE!
java.lang.AssertionError:

Expecting actual not to be null
        at com.quorum.tessera.config.JaxbConfigFactoryTest.cantAppendToPasswordFileThrowsError(JaxbConfigFactoryTest.java:100)

[INFO] Running com.quorum.tessera.config.ConfigTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.quorum.tessera.config.ConfigTest
[INFO] Running com.quorum.tessera.config.adapters.KeyDataAdapterTest
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in com.quorum.tessera.config.adapters.KeyDataAdapterTest
[INFO] Running com.quorum.tessera.config.adapters.PrivateKeyTypeAdapterTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.quorum.tessera.config.adapters.PrivateKeyTypeAdapterTest
[INFO] Running com.quorum.tessera.config.adapters.PathAdapterTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.quorum.tessera.config.adapters.PathAdapterTest
[INFO] Running com.quorum.tessera.config.HashicorpKeyVaultConfigTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in com.quorum.tessera.config.HashicorpKeyVaultConfigTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   JaxbConfigFactoryTest.cantAppendToPasswordFileThrowsError:100
Expecting actual not to be null
[INFO]
[ERROR] Tests run: 325, Failures: 1, Errors: 0, Skipped: 0

Then the remaining parts are all skipped and the installation exits.
How can I fix it?

**Comment by namtruong** [comment]
The test above tests a specific case where file is not writable. Running the build with privilege will cause this test to fail. 
Please make sure mvn build wasn't run as root. Or you can do a build with tests skip i.e. `-DskipTests=true`
