### ISSUE TITLE
Getting Out of memory

### ISSUE THREAD

**Issue by SriramRS** [Consensys-Incorporated/tessera#742]
**System information**

Geth version: 1.8.12-stable

OS & Version: Linux/Ubuntu

Branch, Commit Hash or Release: Quorum 2.2.1

**Description**

Getting out of memory exception in tessera while sending raw private transaction from web3j quorum.

_I am using quorum 7 nodes docker setup with raft `consensus` to create the network.

Please find below the error log file in tessera docker container.[tessera_error_log.txt](https://github.com/jpmorganchase/tessera/files/3165731/tessera_error_log.txt)

_Note :  Errors occurs only after adding blocks for certain period of time(more than 2 weeks)._

**Comment by prd-fox** [comment]
After talking offline, the cause was limiting the memory of Tessera to 128mb. After increasing the heap size, the issue went away.
