### ISSUE TITLE
Not able to locate files while running tessera

### ISSUE THREAD

**Issue by subhasisbanik** [Consensys-Incorporated/tessera#745]
I am trying to set up quorum-7 nodes which has a prerequisite of Tessera.
I am struck while trying to run 
https://github.com/jpmorganchase/tessera#running-tessera

The path seems to have changed for the target jar and config.json is also not found.
Could you please fix this?

**Comment by chris-j-h** [comment]
After running `mvn install` the Tessera jars are now located in `/tessera-dist` directory.  

Thanks for pointing this out, I'll update the README.

`tessera-dist/tessera-app` is a "fat" jar and contains all dependencies you may need to run Tessera.  `tessera-dist/tessera-simple` is a stripped-down jar allowing you to add only the dependencies you need to classpath depending on how you are configuring/using Tessera.  [tessera-dist README](https://github.com/jpmorganchase/tessera/tree/master/tessera-dist)

When running Tessera normally, you will have to create a configfile and provide the path to that yourself.  If using the 7nodes example, the Tessera configfiles are generated as part of the startup scripts so this step is handled for you.  See the [7nodes docs](https://docs.goquorum.com/en/latest/Getting%20Started/Quorum-Examples/#running-the-7nodes-example) for more info.
