### ISSUE TITLE
mvn install security error

### ISSUE THREAD

**Issue by lipka00** [Consensys-Incorporated/tessera#775]
Hello there, I was trying to install Tessera with mvn install, but unfortunately without success because of a security error. In which file I have to add my host to a known host?
Thanks-

Java:
$ java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

Maven:
mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: /usr/local/apache-maven-3.5.4
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-0.43.amzn1.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.14.121-85.96.amzn1.x86_64", arch: "amd64", family: "unix"

-------------------------------------------------------------------------------------------------

[ERROR] Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 1.765 s <<< FAILURE! - in com.quorum.tessera.ssl.context.SSLContextBuilderTest
[ERROR] testBuildUsingPemFiles(com.quorum.tessera.ssl.context.SSLContextBuilderTest)  Time elapsed: 0.345 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)

[ERROR] testKeyStoreNotExistedThenGenerated(com.quorum.tessera.ssl.context.SSLContextBuilderTest)  Time elapsed: 0.297 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)

[ERROR] testBuildForCASignedCertificates(com.quorum.tessera.ssl.context.SSLContextBuilderTest)  Time elapsed: 0.317 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)

[ERROR] testBuildForAllCertificates(com.quorum.tessera.ssl.context.SSLContextBuilderTest)  Time elapsed: 0.154 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)

[ERROR] testBuildForTrustOnFirstUse(com.quorum.tessera.ssl.context.SSLContextBuilderTest)  Time elapsed: 0.261 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)

[ERROR] testBuildForCAOrTOFU(com.quorum.tessera.ssl.context.SSLContextBuilderTest)  Time elapsed: 0.229 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)

[ERROR] testBuildForWhiteList(com.quorum.tessera.ssl.context.SSLContextBuilderTest)  Time elapsed: 0.158 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.context.SSLContextBuilderTest.setUp(SSLContextBuilderTest.java:62)

[INFO] Running com.quorum.tessera.ssl.context.ClientSSLContextFactoryTest
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.594 s - in com.quorum.tessera.ssl.context.ClientSSLContextFactoryTest
[INFO] Running com.quorum.tessera.ssl.context.model.SSLContextPropertiesTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.513 s - in com.quorum.tessera.ssl.context.model.SSLContextPropertiesTest
[INFO] Running com.quorum.tessera.ssl.context.ServerSSLContextFactoryTest
[INFO] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.08 s - in com.quorum.tessera.ssl.context.ServerSSLContextFactoryTest
[INFO] Running com.quorum.tessera.ssl.strategy.TrustModeTest
[ERROR] Tests run: 6, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 1.038 s <<< FAILURE! - in com.quorum.tessera.ssl.strategy.TrustModeTest
[ERROR] testNone(com.quorum.tessera.ssl.strategy.TrustModeTest)  Time elapsed: 0.196 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testNone(TrustModeTest.java:35)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testNone(TrustModeTest.java:35)

[ERROR] testTOFU(com.quorum.tessera.ssl.strategy.TrustModeTest)  Time elapsed: 0.257 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testTOFU(TrustModeTest.java:62)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testTOFU(TrustModeTest.java:62)

[ERROR] testWhiteList(com.quorum.tessera.ssl.strategy.TrustModeTest)  Time elapsed: 0.159 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testWhiteList(TrustModeTest.java:44)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testWhiteList(TrustModeTest.java:44)

[ERROR] testCA(com.quorum.tessera.ssl.strategy.TrustModeTest)  Time elapsed: 0.158 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testCA(TrustModeTest.java:53)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testCA(TrustModeTest.java:53)

[ERROR] testCAOrTOFU(com.quorum.tessera.ssl.strategy.TrustModeTest)  Time elapsed: 0.264 s  <<< ERROR!
java.net.UnknownHostException: ip-10-104-182-221: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testCAOrTOFU(TrustModeTest.java:71)
Caused by: java.net.UnknownHostException: ip-10-104-182-221: Name or service not known
        at com.quorum.tessera.ssl.strategy.TrustModeTest.testCAOrTOFU(TrustModeTest.java:71)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   SSLContextBuilderTest.setUp:62 » UnknownHost ip-10-104-182-221: ip-10-104-182-...
[ERROR]   SSLContextBuilderTest.setUp:62 » UnknownHost ip-10-104-182-221: ip-10-104-182-...
[ERROR]   SSLContextBuilderTest.setUp:62 » UnknownHost ip-10-104-182-221: ip-10-104-182-...
[ERROR]   SSLContextBuilderTest.setUp:62 » UnknownHost ip-10-104-182-221: ip-10-104-182-...
[ERROR]   SSLContextBuilderTest.setUp:62 » UnknownHost ip-10-104-182-221: ip-10-104-182-...
[ERROR]   SSLContextBuilderTest.setUp:62 » UnknownHost ip-10-104-182-221: ip-10-104-182-...
[ERROR]   SSLContextBuilderTest.setUp:62 » UnknownHost ip-10-104-182-221: ip-10-104-182-...
[ERROR]   TrustModeTest.testCA:53 » UnknownHost ip-10-104-182-221: ip-10-104-182-221: Na...
[ERROR]   TrustModeTest.testCAOrTOFU:71 » UnknownHost ip-10-104-182-221: ip-10-104-182-2...
[ERROR]   TrustModeTest.testNone:35 » UnknownHost ip-10-104-182-221: ip-10-104-182-221: ...
[ERROR]   TrustModeTest.testTOFU:62 » UnknownHost ip-10-104-182-221: ip-10-104-182-221: ...
[ERROR]   TrustModeTest.testWhiteList:44 » UnknownHost ip-10-104-182-221: ip-10-104-182-...
[ERROR]   HostnameUtilTest.testGetHostIpAddress:21 » UnknownHost ip-10-104-182-221: ip-1...
[ERROR]   HostnameUtilTest.testGetHostName:14 » UnknownHost ip-10-104-182-221: ip-10-104...
[ERROR]   TlsUtilsTest.testGenerateKeys:40 » UnknownHost ip-10-104-182-221: ip-10-104-18...
[INFO]
[ERROR] Tests run: 74, Failures: 0, Errors: 15, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] tessera 0.10-SNAPSHOT .............................. SUCCESS [  5.199 s]
[INFO] argon2 ............................................. SUCCESS [ 21.274 s]
[INFO] tests .............................................. SUCCESS [  1.380 s]
[INFO] test-util .......................................... SUCCESS [  1.130 s]
[INFO] shared ............................................. SUCCESS [  9.271 s]
[INFO] service-locator .................................... SUCCESS [  0.966 s]
[INFO] service-locator-api ................................ SUCCESS [  0.951 s]
[INFO] encryption ......................................... SUCCESS [  0.884 s]
[INFO] encryption-api ..................................... SUCCESS [  8.199 s]
[INFO] encryption-jnacl ................................... SUCCESS [  6.018 s]
[INFO] config ............................................. SUCCESS [ 51.950 s]
[INFO] cli ................................................ SUCCESS [  1.288 s]
[INFO] cli-api ............................................ SUCCESS [ 10.428 s]
[INFO] key-vault .......................................... SUCCESS [  0.778 s]
[INFO] key-vault-api ...................................... SUCCESS [  2.879 s]
[INFO] key-generation ..................................... SUCCESS [  9.196 s]
[INFO] config-cli ......................................... SUCCESS [03:06 min]
[INFO] security ........................................... FAILURE [ 10.879 s]
[INFO] server ............................................. SKIPPED
[INFO] server-api ......................................... SKIPPED
[INFO] server-utils ....................................... SKIPPED
[INFO] jersey-server ...................................... SKIPPED
[INFO] jaxrs-client-unixsocket ............................ SKIPPED
[INFO] jaxrs-client ....................................... SKIPPED
[INFO] admin-cli .......................................... SKIPPED
[INFO] tessera-dist ....................................... SKIPPED
[INFO] tessera-launcher ................................... SKIPPED
[INFO] key-pair-converter ................................. SKIPPED
[INFO] enclave ............................................ SKIPPED
[INFO] enclave-api ........................................ SKIPPED
[INFO] tessera-core ....................................... SKIPPED
[INFO] jaxrs-service ...................................... SKIPPED
[INFO] enclave-server ..................................... SKIPPED
[INFO] service-locator-spring ............................. SKIPPED
[INFO] enclave-jaxrs ...................................... SKIPPED
[INFO] grpc ............................................... SKIPPED
[INFO] grpc-api ........................................... SKIPPED
[INFO] grpc-service ....................................... SKIPPED
[INFO] grpc-server ........................................ SKIPPED
[INFO] azure-key-vault .................................... SKIPPED
[INFO] hashicorp-key-vault ................................ SKIPPED
[INFO] tessera-app ........................................ SKIPPED
[INFO] tessera-simple ..................................... SKIPPED
[INFO] tessera-grpc ....................................... SKIPPED
[INFO] config-migration ................................... SKIPPED
[INFO] ddls ............................................... SKIPPED
[INFO] acceptance-test .................................... SKIPPED
[INFO] jmeter-test ........................................ SKIPPED
[INFO] encryption-kalium .................................. SKIPPED
[INFO] data-migration 0.10-SNAPSHOT ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:31 min
[INFO] Finished at: 2019-06-03T09:08:15+02:00
[INFO] ------------------------------------------------------------------------

**Comment by namtruong** [comment]
@lipka00 the issue seems to be because the HostnameUtil cannot work out your hostname (for certificate generation), one possible reason would be hostname is not in file `/etc/hosts`.
If this is the case you can modify the file to have `127.0.0.1  [hostname] localhost`

**Comment by namtruong** [comment]
Close due to inactivity
