### ISSUE TITLE
Failed to execute goal on project enclave-api: Could not resolve dependencies for project com.jpmorgan.quorum

### ISSUE THREAD

**Issue by jiebanghan** [Consensys-Incorporated/tessera#799]
when I run mvn clean install -Dcheckstyle.skip=true  -DskipTests, then it shows me below,can you help me ?thank you 

[WARNING] The POM for com.jpmorgan.quorum:key-pair-converter:jar:0.10-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for tessera 0.10-SNAPSHOT:
[INFO] 
[INFO] tessera ............................................ SUCCESS [  7.102 s]
[INFO] argon2 ............................................. SUCCESS [  6.343 s]
[INFO] tests .............................................. SUCCESS [  1.839 s]
[INFO] test-util .......................................... SUCCESS [  2.914 s]
[INFO] shared ............................................. SUCCESS [  5.077 s]
[INFO] service-locator .................................... SUCCESS [  1.593 s]
[INFO] service-locator-api ................................ SUCCESS [  1.972 s]
[INFO] encryption ......................................... SUCCESS [  1.788 s]
[INFO] encryption-api ..................................... SUCCESS [  2.829 s]
[INFO] encryption-jnacl ................................... SUCCESS [  3.736 s]
[INFO] config ............................................. SUCCESS [  6.693 s]
[INFO] cli ................................................ SUCCESS [  1.555 s]
[INFO] cli-api ............................................ SUCCESS [  3.515 s]
[INFO] key-vault .......................................... SUCCESS [  1.636 s]
[INFO] key-vault-api ...................................... SUCCESS [  3.446 s]
[INFO] key-generation ..................................... SUCCESS [  2.639 s]
[INFO] config-cli ......................................... SUCCESS [  4.380 s]
[INFO] security ........................................... SUCCESS [  2.714 s]
[INFO] server ............................................. SUCCESS [  0.800 s]
[INFO] server-api ......................................... SUCCESS [  2.428 s]
[INFO] server-utils ....................................... SUCCESS [  1.832 s]
[INFO] jersey-server ...................................... SUCCESS [  3.599 s]
[INFO] jaxrs-client-unixsocket ............................ SUCCESS [  2.985 s]
[INFO] jaxrs-client ....................................... SUCCESS [  2.214 s]
[INFO] admin-cli .......................................... SUCCESS [  2.592 s]
[INFO] tessera-dist ....................................... SUCCESS [  1.196 s]
[INFO] tessera-launcher ................................... SUCCESS [  1.692 s]
[INFO] enclave ............................................ SUCCESS [  0.795 s]
[INFO] enclave-api ........................................ FAILURE [  0.057 s]
[INFO] tessera-admin ...................................... SKIPPED
[INFO] tessera-partyinfo .................................. SKIPPED
[INFO] tessera-core ....................................... SKIPPED
[INFO] jaxrs-service ...................................... SKIPPED
[INFO] enclave-server ..................................... SKIPPED
[INFO] service-locator-spring ............................. SKIPPED
[INFO] enclave-jaxrs ...................................... SKIPPED
[INFO] grpc ............................................... SKIPPED
[INFO] grpc-api ........................................... SKIPPED
[INFO] grpc-service ....................................... SKIPPED
[INFO] grpc-server ........................................ SKIPPED
[INFO] azure-key-vault .................................... SKIPPED
[INFO] hashicorp-key-vault ................................ SKIPPED
[INFO] tessera-app ........................................ SKIPPED
[INFO] tessera-simple ..................................... SKIPPED
[INFO] tessera-grpc ....................................... SKIPPED
[INFO] config-migration ................................... SKIPPED
[INFO] ddls ............................................... SKIPPED
[INFO] acceptance-test .................................... SKIPPED
[INFO] jmeter-test ........................................ SKIPPED
[INFO] encryption-kalium .................................. SKIPPED
[INFO] data-migration ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:25 min
[INFO] Finished at: 2019-06-14T04:37:01-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project enclave-api: Could not resolve dependencies for project com.jpmorgan.quorum:enclave-api:jar:0.10-SNAPSHOT: Could not find artifact com.jpmorgan.quorum:key-pair-converter:jar:0.10-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :enclave-api

**Comment by prd-fox** [comment]
Hey. This was an issue after a merge yesterday, but we reverted it today. You must have checked or updated the project at just the wrong time :P

Can you pull latest master and try again?

**Comment by jiebanghan** [comment]
thank you ,I will try it.

**Comment by jiebanghan** [comment]
ok, done.

**Comment by jiebanghan** [comment]
but after compilation I hava no config.json, how to achieve it ?thank you .

**Comment by prd-fox** [comment]
You need to create your own, based on your network setup, and what features you require.

An example setup is provided [here](https://github.com/jpmorganchase/quorum-examples/blob/master/README.md#running-the-7nodes-example). After running `./raft-init.sh`, you will see a sample config located at `./qdata/c1/tessera-config-09-1.json`.

**Comment by jiebanghan** [comment]
thank you very much .

**Comment by prd-fox** [comment]
Since all questions seemed to be solved, I am closing this issue. If you have any other questions, feel free to create a new issue. Thanks.
