### ISSUE TITLE
Error: EOF undefined while trying to transact privately between 2 peers

### ISSUE THREAD

**Issue by subhasisbanik** [Consensys-Incorporated/tessera#802]
Geth version: 1.8.18-stable
Quorum version: 2.2.3
Go:1.10.3
Tessera version: 0.9

I have used the latest tessera docs
https://goquorum.readthedocs.io/en/latest/Privacy/Tessera/Configuration/Configuration%20Overview/

To set up 3 peers.
Below is the tessera-config.json for node 1(similar for node 2 and node 3 with only changes in ip):
----------------------------------------------------------------------------
{
    "useWhiteList": false,
    "jdbc": {
        "username": "sa",
        "password": "",
        "url": "jdbc:h2:/home/ubuntu/node/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
        "autoCreateTables": true
    },
    "serverConfigs": [
        {
            "app": "P2P",
            "enabled": true,
            "serverAddress": "http://ip1:9001",
            "bindingAddress": "http://0.0.0.0:9001",
            "sslConfig": {
                "tls": "OFF"
            },
            "communicationType": "REST"
        },
        {
            "app": "Q2T",
            "enabled": true,
            "serverAddress": "unix:/home/ubuntu/node/datadir/tm.ipc",
            "communicationType": "REST"
        }
    ],

    "peer": [
     {
    "url": "http://ip1:9001"
  },
  {
    "url": "http://ip2:9001"
  },
  {
    "url": "http://ip3:9001"
  }
    ],
  "keys": {
        "passwords": [],
        "keyData": [
            {
                "privateKeyPath": "/home/ubuntu/node/tessera-key-pair/node.key",
                "publicKeyPath": "/home/ubuntu/node/tessera-key-pair/node.pub"
            }
        ]
    },

    "alwaysSendTo": [],

    "unixSocketFile": "/home/ubuntu/node/datadir/tm.ipc"
---------------------------------------------------------------------------------
I have also put the below commands to turn up geth(similar for node 2 and node 3):
----------------------------------------------------------------------------------
ARGS="--nodiscover --verbosity 5 --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints"
PRIVATE_CONFIG=datadir/tm.ipc
nohup geth --datadir datadir $ARGS --raftport 50401 --rpcport 22000 --port 21000 --identity 'QUORUM01' --unlock 0 --password passwords.txt 2>>datadir/logs/node.log &
-------------------------------------------------------------------------------
I have also did admin.addPeer() from node 1 using node 2 and node 3 enode.
Now the problem is I am not able to transact private transactions from geth console with passing "privateFor:[public key of node 2]" from node 1.
However I am able to successfully transact public transactions from all the peers.

Please help!!!!

**Comment by subhasisbanik** [comment]
Also saw this error in geth log:
ERROR[06-15|04:52:25.116] goroutine 375 [running]:
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func1(0xc421718870, 0x123ed80, 0xc420d79810)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:132 +0xf4
panic(0xf24980, 0x19a9290)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).SendTransaction(0xc420194d20, 0x1238d20, 0xc420fed7d0, 0x84b3a2ab5eb76257, 0xd1c707f1902b4e46, 0xd218ef1f, 0x0, 0xc420fe3db8, 0x0, 0x0, ...)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:1384 +0x830
reflect.Value.call(0xc420440b80, 0xc42000ff58, 0x13, 0x1088c8d, 0x4, 0xc420fc0fc0, 0x3, 0x4, 0xc420fed7d0, 0xc420fc0fc0, ...)
        /usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc420440b80, 0xc42000ff58, 0x13, 0xc420fc0fc0, 0x3, 0x4, 0x1, 0x1, 0x1)
        /usr/local/go/src/reflect/value.go:308 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc421718870, 0x1238c60, 0xc420361bc0, 0x123ed80, 0xc420d79810, 0xc420fc0f60, 0xc420d79880, 0x0, 0xf0e740)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:313 +0x8fa
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc421718870, 0x1238c60, 0xc420361bc0, 0x123ed80, 0xc420d79810, 0xc420fc0f60)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:334 +0x1a6
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest(0xc421718870, 0x1238d20, 0xc420fed680, 0x123ed80, 0xc420d79810, 0x1092001, 0x1, 0x0, 0x0)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:192 +0x370
github.com/ethereum/go-ethereum/rpc.(*Server).ServeSingleRequest(0xc421718870, 0x1238d20, 0xc420fed680, 0x123ed80, 0xc420d79810, 0x1)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:223 +0x65
github.com/ethereum/go-ethereum/rpc.(*Server).ServeHTTP(0xc421718870, 0x12373e0, 0xc4202108c0, 0xc420d73e00)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:253 +0x4c2
github.com/ethereum/go-ethereum/rpc.(*virtualHostHandler).ServeHTTP(0xc42038a7c0, 0x12373e0, 0xc4202108c0, 0xc420d73e00)
        /home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/http.go:311 +0x204
net/http.serverHandler.ServeHTTP(0xc42173c0d0, 0x12373e0, 0xc4202108c0, 0xc420d73e00)
        /usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4216e61e0, 0x1238c60, 0xc420361640)
        /usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x27b

**Comment by namtruong** [comment]
Can you please also share Tessera logs?

**Comment by subhasisbanik** [comment]
11:47:34.704 [qtp391479787-23] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK
11:47:36.705 [qtp391479787-26] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo
11:47:36.708 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo/validate
11:47:36.711 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo/validate
11:47:36.711 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo/validate : 200 OK
11:47:36.712 [qtp391479787-26] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo
11:47:36.712 [qtp391479787-26] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK
11:47:38.713 [qtp391479787-22] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo
11:47:38.717 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo/validate
11:47:38.720 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo/validate
11:47:38.720 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo/validate : 200 OK
11:47:38.720 [qtp391479787-22] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo
11:47:38.720 [qtp391479787-22] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK
11:47:40.721 [qtp391479787-19] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo
11:47:40.725 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo/validate
11:47:40.728 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo/validate
11:47:40.728 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo/validate : 200 OK
11:47:40.729 [qtp391479787-19] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo
11:47:40.729 [qtp391479787-19] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK
11:47:42.730 [qtp391479787-25] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo
11:47:42.733 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo/validate
11:47:42.736 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo/validate
11:47:42.736 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo/validate : 200 OK
11:47:42.737 [qtp391479787-25] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo
11:47:42.737 [qtp391479787-25] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK
11:47:44.738 [qtp391479787-21] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo
11:47:44.742 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo/validate
11:47:44.745 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo/validate
11:47:44.745 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo/validate : 200 OK
11:47:44.746 [qtp391479787-21] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo
11:47:44.746 [qtp391479787-21] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK
11:47:46.747 [qtp391479787-23] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo
11:47:46.750 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo/validate
11:47:46.753 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo/validate
11:47:46.753 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo/validate : 200 OK
11:47:46.754 [qtp391479787-23] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo
11:47:46.754 [qtp391479787-23] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK
11:47:48.755 [qtp391479787-26] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo
11:47:48.758 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo/validate
11:47:48.761 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo/validate
11:47:48.761 [qtp391479787-24] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo/validate : 200 OK
11:47:48.762 [qtp391479787-26] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo
11:47:48.762 [qtp391479787-26] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK

**Comment by namtruong** [comment]
The above are just normal partyinfo synchronising messages. Please check for any error messages in Tessera log during the time you sent the private transaction

**Comment by subhasisbanik** [comment]
Yes that is the thing, except for the panic in geth log, there isnt anything in tessera.

**Comment by namtruong** [comment]
It looks like you have Quorum and Tessera both up and running. Tessera nodes are also in sync with each other  so nothing seems wrong. 
However in this case Quorum is not connecting to Tessera somehow. I would suggest checking the location of the ipc files if they are correct - might be worth running a curl via ipc i.e. `curl http://localhost:9081/upcheck --unix-socket <ipcfile>` and check the response

**Comment by subhasisbanik** [comment]
@namtruong : 
I ran :
curl http://localhost:9081/upcheck --unix-socket /home/ubuntu/node/datadir/tm.ipc
and got :
I'm up!

Is this the correct response?
I think I noticed that is different:
I ran the script with PRIVATE_CONFIG and geth command in different lines:

ARGS="--nodiscover --verbosity 5 --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft"
PRIVATE_CONFIG=datadir/tm.ipc
nohup geth --datadir datadir $ARGS --raftport 50401 --rpcport 22000 --port 21000 --identity 'QUORUM01' --unlock 0 --password passwords.txt 2>>datadir/logs/node.log &

Does this make any change or create an issue?

Please help!!

**Comment by namtruong** [comment]
That's the correct response so Tessera is also up and running. I'm not sure what else could be wrong to be honest. Please can you send details the steps/commands on how you sent transactions?

**Comment by subhasisbanik** [comment]
I am trying to run the web3deploy for a simple getter setter contract as below:
var testContract = web3.eth.contract([{"constant":false,"inputs":[{"name":"_val","type":"uint256"}],"name":"setValue","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"getVal","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"}]);
var test = testContract.new(
   {
     from: web3.eth.accounts[0], 
     data: '0x608060405234801561001057600080fd5b5060e68061001f6000396000f3fe6080604052600436106043576000357c01000000000000000000000000000000000000000000000000000000009004806355241077146048578063e1cb0e5214607f575b600080fd5b348015605357600080fd5b50607d60048036036020811015606857600080fd5b810190808035906020019092919050505060a7565b005b348015608a57600080fd5b50609160b1565b6040518082815260200191505060405180910390f35b8060008190555050565b6000805490509056fea165627a7a72305820f161fc19351da28969123b2256d656fadc5c5871bd843e768deea5f52f6346540029', 
     gas: '4700000' ,privateFor:['DBQeaJmFdawHJn/rMS7ioDmu50lsOo8SH5ebeePgiAM=']
   }, function (e, contract){
    console.log(e, contract);
    if (typeof contract.address !== 'undefined') {
         console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);
    }
 })

Here I have added the node.pub in the publicFor for the node I want to be a part of.

Is there anything I need to do more?

**Comment by subhasisbanik** [comment]
Also in nodes which are not calling private transaction, I see the below log:

TRACE[06-19|19:11:15.091] New dial task                            task="staticdial bf1ebedbc5994397 <otherip>:0"
TRACE[06-19|19:11:15.092] Dial error                               task="staticdial bf1ebedbc5994397 <otherip>:0" err="dial tcp <otherip>:0: connect: connection refused"

Note, I have replaced my ip with <otherip>.

**Comment by chris-j-h** [comment]
> I ran the script with PRIVATE_CONFIG and geth command in different lines:
> 
> ARGS="--nodiscover --verbosity 5 --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft"
> PRIVATE_CONFIG=datadir/tm.ipc
> nohup geth --datadir datadir $ARGS --raftport 50401 --rpcport 22000 --port 21000 --identity 'QUORUM01' --unlock 0 --password passwords.txt 2>>datadir/logs/node.log &
> 
> Does this make any change or create an issue?

This will likely cause issues, `PRIVATE_CONFIG` is an environment variable that `geth` needs in order to use the privacy manager.  

If it's on a separate line to the `geth` command then `geth` won't have access to that environment variable.  Try again either with `PRIVATE_CONFIG=datadir/tm.ipc` on the same line or if you want it on a separate line try `export PRIVATE_CONFIG=datadir/tm.ipc`

**Comment by subhasisbanik** [comment]
@chris-j-h Thanks for the help. That worked. I am able to mine private transactions. Hence closing this issue.
