### ISSUE TITLE
Move the advertised address out of server configuration

### ISSUE THREAD

**Issue by prd-fox** [Consensys-Incorporated/tessera#807]
Currently, the URL that is advertised to other peers with our public keys is taken from the P2P server configuration, as the `serverAddress` property.
In order to be able to bind to a different address, the `bindingAddress` property was introduced.

Since the advertised address isn't directly linked to the server configuration (although there is an indirect link to the `P2P` server), it could make sense to move this "advertised address" to a node level property instead of server level. Then, we can remove the distinction between `serverAddress` and `bindingAddress`, only needing one of them (which would be the `bindingAddress`).

This would overall reduce the confusion that can arise between the properties, whilst keeping the server setup distinct from the rest of the node.

**Comment by SatpalSandhu61** [comment]
After discussion, decided not to make any code changes for this. The bindingAddress and serverAddress are associated with the server config and might be needed for other server types (such as ThirdParty).
Will instead add documentation to clarify the use of bindingAddress.
