### ISSUE TITLE
Issue when geth is pushed with large number of transactions

### ISSUE THREAD

**Issue by subhasisbanik** [Consensys-Incorporated/tessera#808]
I am running a web3j layer to push public transactions sequentially to a 10 peer quorum network continously with 8 core 15GB RAM and 100GB SSDper node.
Now after approx 50k txns per node, I observe that the geth stops responding with contract addresses(i.e. transaction confirmation) though there are no errors in log.
I have to stop and start geth to make it up and running.
Now with that maintenance, after a total of 2.6million txns, I observed that the hdd is filled completely and hence geth stops.
Can anyone help with this behavior of geth and any possible resolutions around it?

**Comment by Krish1979** [comment]
Could you please raise this issue against Quorum repo.,
