### ISSUE TITLE
Unique index or primary key violation error on private transactions

### ISSUE THREAD

**Issue by vdamle** [Consensys-Incorporated/tessera#809]
Quorum version: 2.2.3
Tessera version: 0.8 + https://github.com/jpmorganchase/tessera/pull/688
JDK: openjdk 11.0.3

We are hitting the following error when participants in the network send private transactions to one another:

```
02:55:55.155 [grizzly-http-server-0] INFO  c.q.tessera.api.filter.LoggingFilter - Enter Request : POST : /push
02:55:55.157 [grizzly-http-server-0] INFO  c.q.t.t.EncryptedTransactionDAOImpl - Stored transaction XNWP6Xa1xj63ZnVhnggQLxVy8RAKZtMvALhix63ndOg5RDtiU2q9jRE/H7xh4pTd16syyct/K0YvpazyUKxxEg==
02:55:55.164 [grizzly-http-server-0] INFO  c.q.t.t.TransactionManagerImpl - Stored payload with hash XNWP6Xa1xj63ZnVhnggQLxVy8RAKZtMvALhix63ndOg5RDtiU2q9jRE/H7xh4pTd16syyct/K0YvpazyUKxxEg==
02:55:55.249 [grizzly-http-server-0] WARN  eclipselink.logging.all - Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "CONSTRAINT_D_INDEX_8 ON PUBLIC.ENCRYPTED_TRANSACTION(HASH) VALUES (X'5cd58fe976b5c63eb76675619e08102f1572f1100a66d32f00b862c7ade774e839443b62536abd8d113f1fbc61e294ddd7ab32c9cb7f2b462fa5acf250ac7112', 747)"; SQL statement:
INSERT INTO ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD, TIMESTAMP, HASH) VALUES (?, ?, ?) [23505-197]
Error Code: 23505
Call: INSERT INTO ENCRYPTED_TRANSACTION (ENCODED_PAYLOAD, TIMESTAMP, HASH) VALUES (?, ?, ?)
        bind => [3 parameters bound]
Query: InsertObjectQuery(com.quorum.tessera.transaction.model.EncryptedTransaction@8f1124fc)
02:55:55.251 [grizzly-http-server-0] ERROR c.q.t.a.e.DefaultExceptionMapper - Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.3.v20180807-4be1041): org.eclipse.persistence.exceptions.DatabaseException
```

Some details about the chain:

* Each node runs with it's own instance of H2 db. Nodes use a CA signed certificate
* Nodes are migrated from constellation to tessera
* Submission of transactions after migration fails with the above error

**Comment by namtruong** [comment]
Hi - can you upload full logs of both the node that's sending transactions and the privateFor node. Also how the transactions are being submitted... We'll take a look thanks

**Comment by vdamle** [comment]
[constellation-node1.log](https://github.com/jpmorganchase/tessera/files/3335388/constellation-node1.log)
[constellation-node2.log](https://github.com/jpmorganchase/tessera/files/3335389/constellation-node2.log)

From the logs it looks like the transaction `vcjlJmzPyCW+wSd/xIJXi9IxYfPrZwrfJ1+8C8yo1JSWR2eikTSZoJPMB0oq0v/8CitxtMCnBaZOdfBt7mCQrw==` was submitted in constellation land. I can't quite tell if the submission during migration is what is throwing the errors above.

**Comment by Krish1979** [comment]
it could well be. I think there is no conclusive evidence that this is from send request and so this is down to time of migration and restart. Like discussed, please upgrade to Tessera 0.9 where auto sync is disabled and you shouldn't get these errors.
