### ISSUE TITLE
Transaction manager resend method

### ISSUE THREAD

**Issue by melowe** [Consensys-Incorporated/tessera#838]
The code in the resend method needs rewriting so that the logic it clearer and there are less logical branches. Starting with test rather than retro fitting one will reveal the high branch count and complexity. 

1. Dispatch to separate function that handles ALL from INDIVIDUAL resends. 
2. Find and implement a more elegant means of buffering resends. 

Create helper/delegate objects if required. The code needs to read well enough for other people to work with the code.

**Comment by Krish1979** [comment]
To be worked on next
