### ISSUE TITLE
Use PicoCLI instead of commons-cli

### ISSUE THREAD

**Issue by prd-fox** [Consensys-Incorporated/tessera#874]
PicoCLI has better support for handling command line args, including:

- better help output
- strong type conversions
- automatic subcommand handling (routing logic)
- exception and exit code handling (although we may continue to use our own)
- keeps options contained to where they are used, instead of defined up front

It could be worth investigating if this provides any benefit, especially if we are going to add more subcommands as in https://github.com/jpmorganchase/tessera/issues/872 or https://github.com/jpmorganchase/tessera/issues/871.

There are already quite a few options in the `DefaultCliAdapter`, particularly around key generation, that could be split out.

**Comment by melowe** [comment]
As an extension to this task, changing the CLI framework also means that the current tests might me less relevant. For CLI stuff it would be great is testing was from the provision of CLI options and verifying the output, which is perhaps a departure to traditional unit tests. 

Also, remove IO dependencies and abstract out. tests should interact with api objects and not have filesystem dependencies. FilesDelegate and other util objects can be used and mocked out for tests.

**Comment by prd-fox** [comment]
Finished in https://github.com/jpmorganchase/tessera/pull/946
