### ISSUE TITLE
from field is encrypted?

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/tessera#903]
Hi there,
We are sending private transactions and we detect that the "from" is different from the account we are sending the transactions

Any idea?

**Comment by prd-fox** [comment]
Are you referring to the `from` account of the Quorum transaction?

**Comment by dvgoyeneche** [comment]
Yes, on public transactions that from would be the correct one, but now that we're trying private transactions that "from" field is different every time.

**Comment by prd-fox** [comment]
I've moved this issue to the repo where the issue is caused, since this isn't a Tessera issue @dvgoyeneche https://github.com/jpmorganchase/quorum.js/issues/24
