### ISSUE TITLE
How to set log level

### ISSUE THREAD

**Issue by yjfcn** [Consensys-Incorporated/tessera#908]
Does anyone know how to set default log level from INTO to WARN? Thanks!

**Comment by prd-fox** [comment]
You may provide the system property `-Dverbosity=WARN` to only receive warnings and errors.

Alternatively, for a more bespoke solution for a particular log message that is causing issues, you may provide your own logback file as shown here:
http://logback.qos.ch/manual/configuration.html#configFileProperty

**Comment by yjfcn** [comment]
@prd-fox Thank you very much!
