### ISSUE TITLE
mvn install failure

### ISSUE THREAD

**Issue by mygoodboy** [Consensys-Incorporated/tessera#911]
after mvn package -Dmaven.test.skip=true:
[INFO] tessera 0.11-SNAPSHOT .............................. SUCCESS [  1.694 s]
[INFO] shared ............................................. SUCCESS [  1.389 s]
[INFO] argon2 ............................................. SUCCESS [  0.276 s]
[INFO] tests .............................................. SUCCESS [  0.512 s]
[INFO] test-util .......................................... SUCCESS [  0.193 s]
[INFO] service-locator .................................... SUCCESS [  0.118 s]
[INFO] service-locator-api ................................ SUCCESS [  0.166 s]
[INFO] encryption ......................................... SUCCESS [  0.125 s]
[INFO] encryption-api ..................................... SUCCESS [  0.317 s]
[INFO] encryption-jnacl ................................... SUCCESS [  0.186 s]
[INFO] config ............................................. FAILURE [  0.562 s]
[INFO] cli ................................................ SKIPPED
[INFO] cli-api ............................................ SKIPPED
[INFO] key-vault .......................................... SKIPPED
[INFO] key-vault-api ...................................... SKIPPED
ERROR:

[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.3:check (check) on project config: Coverage checks have not been met. See log for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :config

environment:
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /opt/apache-maven-3.5.4
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-62-generic", arch: "amd64", family: "unix"

**Comment by namtruong** [comment]
Hi, if you don't want to run the tests please use `-DskipTests`

**Comment by namtruong** [comment]
Also, include `clean` in your `mvn` command, otherwise jacoco will use the incomplete coverage of a previous run and still fail, even with tests skipped
