### ISSUE TITLE
mvn clean  failed

### ISSUE THREAD

**Issue by LiQingMuBai** [Consensys-Incorporated/tessera#913]
must be unique: com.google.guava:guava:jar ,please check it 

in pom.xml , find same dependency

`            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>24.1.1-jre</version>
            </dependency>`

**Comment by prd-fox** [comment]
Can you post the output of maven please?

**Comment by namtruong** [comment]
fixed by #922
