### ISSUE TITLE
ThirdParty server hangup problem

### ISSUE THREAD

**Issue by bigstar119** [Consensys-Incorporated/tessera#954]
i made 3 raftbase nodes  with tessera-0.9.4
when startup everything is ok. and i run the example SendRawPrivateTransaction.java deployed a private contract.
then after about 20 minutes later, i run the SendRawPrivateTransaction.java again.
but this time throw exception 

exception messsage like this:
**Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout**
then i visit http://10.10.105.50:9081/upcheck, the client wait very long time and never get response back.

but the P2P port 9001 is ok.

this is my config.json
{
  "useWhiteList": false,
  "peer": [
    {
      "url": "http://10.10.105.50:9001"
    },
    {
      "url": "http://10.10.125.50:9001"
    },
    {
      "url": "http://10.10.125.54:9001"
    }
  ],
  "keys": {
    "keyData": [
      {
        "privateKeyPath": "/home/cpap/app/blockchain/product/node/tm/tm.key",
        "publicKeyPath": "/home/cpap/app/blockchain/product/node/tm/tm.pub"
      }
    ],
    "passwords": []
  },
  "encryptor": {
    "type": "NACL",
    "properties": {}
  },
  "jdbc": {
    "password": "",
    "autoCreateTables": true,
    "url": "jdbc:h2:/home/cpap/app/blockchain/product/node/tm/db1;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
    "username": "sa"
  },
  "serverConfigs": [
    {
      "app": "ThirdParty",
      "cors": {
        "allowedOrigins": [
          "*"
        ],
        "allowedMethods": [
          "GET",
          "OPTIONS"
        ]
      },
      "serverAddress": "http://10.10.105.50:9081",
      "communicationType": "REST",
      "enabled": true
    },
    {
      "app": "Q2T",
      "serverAddress": "unix:/home/cpap/app/blockchain/product/node/tm/tm.ipc",
      "communicationType": "REST",
      "enabled": true
    },
    {
      "app": "P2P",
      "cors": {
        "allowedOrigins": [
          "*"
        ],
        "allowedMethods": [
          "GET",
          "OPTIONS"
        ]
      },
      "sslConfig": {
        "tls": "OFF"
      },
      "serverAddress": "http://10.10.105.50:9001",
      "communicationType": "REST",
      "enabled": true
    }
  ],
  "alwaysSendTo": []
}

what is the problem? and what can i do for it ?

**Comment by SatpalSandhu61** [comment]
Are you seeing any errors in the tessera logs?
If you are able to attach the log for tessera 1 instance then that would help.

**Comment by bigstar119** [comment]
i did not see any error in the tessera.log below is my tessera.log i delete many /partyinfo log because it is to large. before 08:31:08 this morning  i can receive /upcheck response. but after that i can not receive  /upcheck response ,and i can not see any log about  /upcheck . this is my log 

08:29:01.704 [main] INFO  eclipselink.logging.all - EclipseLink, version: Eclipse Persistence Services - 2.7.3.v20180807-4be1041
08:29:01.707 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
08:29:02.095 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
08:29:02.208 [main] INFO  eclipselink.logging.connection - tessera login successful
08:29:02.356 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'tessera'
08:29:02.830 [main] INFO  c.q.t.t.TesseraScheduledExecutor - Starting PartyInfoPoller
08:29:02.841 [main] INFO  c.q.t.t.TesseraScheduledExecutor - Started PartyInfoPoller
08:29:03.329 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @4464ms to org.eclipse.jetty.util.log.Slf4jLog
08:29:03.518 [main] INFO  c.quorum.tessera.server.JerseyServer - Starting http://10.10.125.54:9081
08:29:03.522 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT; built: 2019-04-18T19:45:35.259Z; git: aa1c656c315c011c01e7b21aabb04066635b9f67; jvm 1.8.0_141-b15
08:29:04.469 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.thridparty.ThirdPartyRestApp registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.thridparty.ThirdPartyRestApp will be ignored. 
08:29:04.470 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.thridparty.RawTransactionResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.thridparty.RawTransactionResource will be ignored. 
08:29:04.471 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.api.common.VersionResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.api.common.VersionResource will be ignored. 
08:29:04.471 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.api.common.UpCheckResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.api.common.UpCheckResource will be ignored. 
08:29:04.935 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@31723307{/,null,AVAILABLE}
08:29:05.003 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@57435801{HTTP/1.1,[http/1.1]}{0.0.0.0:9081}
08:29:05.004 [main] INFO  org.eclipse.jetty.server.Server - Started @6138ms
08:29:05.004 [main] INFO  c.quorum.tessera.server.JerseyServer - Started http://10.10.125.54:9081
08:29:05.004 [main] INFO  c.quorum.tessera.server.JerseyServer - WADL http://10.10.125.54:9081/application.wadl
08:29:05.044 [main] INFO  c.quorum.tessera.server.JerseyServer - Starting unix:/home/cpap/app/blockchain/product/node/tm/tm.ipc
08:29:05.044 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT; built: 2019-04-18T19:45:35.259Z; git: aa1c656c315c011c01e7b21aabb04066635b9f67; jvm 1.8.0_141-b15
08:29:05.221 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.q2t.Q2TRestApp registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.q2t.Q2TRestApp will be ignored. 
08:29:05.222 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.q2t.TransactionResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.q2t.TransactionResource will be ignored. 
08:29:05.222 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.api.common.VersionResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.api.common.VersionResource will be ignored. 
08:29:05.222 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.api.common.UpCheckResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.api.common.UpCheckResource will be ignored. 
08:29:05.426 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2744dcae{/,null,AVAILABLE}
08:29:05.829 [main] INFO  o.e.jetty.server.AbstractConnector - Started UnixSocketConnector@7bbcf6f0{HTTP/1.1,[http/1.1]}{/home/cpap/app/blockchain/product/node/tm/tm.ipc}
08:29:05.831 [main] INFO  org.eclipse.jetty.server.Server - Started @6965ms
08:29:05.831 [main] INFO  c.quorum.tessera.server.JerseyServer - Started unix:/home/cpap/app/blockchain/product/node/tm/tm.ipc
08:29:05.831 [main] INFO  c.quorum.tessera.server.JerseyServer - WADL unix:/home/cpap/app/blockchain/product/node/tm/tm.ipc/application.wadl
08:29:05.833 [main] INFO  c.quorum.tessera.server.JerseyServer - Starting http://10.10.125.54:9001
08:29:05.833 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.z-SNAPSHOT; built: 2019-04-18T19:45:35.259Z; git: aa1c656c315c011c01e7b21aabb04066635b9f67; jvm 1.8.0_141-b15
08:29:05.896 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.p2p.ApiResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.p2p.ApiResource will be ignored. 
08:29:05.896 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.p2p.P2PRestApp registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.p2p.P2PRestApp will be ignored. 
08:29:05.896 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.api.common.VersionResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.api.common.VersionResource will be ignored. 
08:29:05.897 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.api.common.UpCheckResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.api.common.UpCheckResource will be ignored. 
08:29:05.897 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.p2p.PartyInfoResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.p2p.PartyInfoResource will be ignored. 
08:29:05.897 [main] WARN  o.g.jersey.internal.inject.Providers - A provider com.quorum.tessera.p2p.TransactionResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider com.quorum.tessera.p2p.TransactionResource will be ignored. 
08:29:05.994 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2ab09943{/,null,AVAILABLE}
08:29:06.011 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@787988f4{HTTP/1.1,[http/1.1]}{0.0.0.0:9001}
08:29:06.011 [main] INFO  org.eclipse.jetty.server.Server - Started @7146ms
08:29:06.011 [main] INFO  c.quorum.tessera.server.JerseyServer - Started http://10.10.125.54:9001
08:29:06.011 [main] INFO  c.quorum.tessera.server.JerseyServer - WADL http://10.10.125.54:9001/application.wadl
08:29:06.062 [qtp2118413714-38] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : GET : /upcheck
08:29:06.069 [qtp2118413714-38] INFO  c.q.t.api.common.UpCheckResource - GET upcheck
08:29:06.079 [qtp2118413714-38] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : GET : /upcheck
08:29:06.080 [qtp2118413714-38] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for upcheck : 200 OK

08:29:11.157 [qtp162821120-42] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : GET : /upcheck
08:29:11.159 [qtp162821120-42] INFO  c.q.t.api.common.UpCheckResource - GET upcheck
08:29:11.159 [qtp162821120-42] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : GET : /upcheck
08:29:11.159 [qtp162821120-42] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for upcheck : 200 OK

08:31:08.451 [qtp2118413714-56] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : GET : /upcheck
08:31:08.452 [qtp2118413714-56] INFO  c.q.t.api.common.UpCheckResource - GET upcheck
08:31:08.452 [qtp2118413714-56] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : GET : /upcheck
08:31:08.452 [qtp2118413714-56] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for upcheck : 200 OK

08:38:04.067 [qtp1149526768-75] INFO  c.q.t.server.jaxrs.LoggingFilter - Enter Request : POST : /partyinfo
08:38:04.068 [qtp1149526768-75] INFO  c.q.t.server.jaxrs.LoggingFilter - Exit Request : POST : /partyinfo
08:38:04.068 [qtp1149526768-75] INFO  c.q.t.server.jaxrs.LoggingFilter - Response for partyinfo : 200 OK

**Comment by bigstar119** [comment]
i think the JerseyServer  on the port 9081 has some problem, and do not accept the http request.
 /upcheck do not have any complex business , the problem may be in the io.

**Comment by bigstar119** [comment]
09:40  3 nodes` p2p server is hangup too. 9001 port unserve any http request. 
curl -s http://10.10.105.50:9001/upcheck
curl -s http://10.10.125.50:9001/upcheck
curl -s http://10.10.125.54:9001/upcheck

crul for 9001 has no response,and client always wait
[root@hadoop-3 node]# netstat -an|grep 9001
tcp6       0      0 :::9001                 :::*                    LISTEN     
tcp6       0      0 10.10.125.54:38268      10.10.125.54:9001       ESTABLISHED
tcp6     859      0 10.10.125.54:9001       10.10.105.50:57902      ESTABLISHED
tcp6     859      0 10.10.125.54:9001       10.10.125.54:38268      ESTABLISHED
tcp6     859      0 10.10.125.54:9001       10.10.125.50:38102      ESTABLISHED
tcp6      89      0 10.10.125.54:9001       10.10.125.54:54246      CLOSE_WAIT 
tcp6      89      0 10.10.125.54:9001       10.10.125.54:54286      CLOSE_WAIT

[root@hadoop-3 node]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core) 
Release:        7.3.1611
Codename:       Core

**Comment by bigstar119** [comment]
nodes.zip is my nodes deployments files
[nodes.zip](https://github.com/jpmorganchase/tessera/files/4028933/nodes.zip)
the dependency in the lib dir like these:
[root@hadoop-3 lib]# pwd
/home/cpap/app/blockchain/product/lib
[root@hadoop-3 lib]# ls
bootnode  geth  tessera.jar
[root@hadoop-3 lib]# 

tessera.jar is tessera-0.9.4
./quorum_init.sh initblockchain
./tessera_start.sh startup tessera
./quorum_start.sh startup quorum

**Comment by bigstar119** [comment]
the quorum-examples:https://github.com/jpmorganchase/quorum-examples on my host has the same problem, when 7nodes startup 10 minutes later, the 9081 port unserved any http request

**Comment by SatpalSandhu61** [comment]
I've tested this and it seems to work fine on the latest Tessera version. Even after 30mins the ThirdParty server still responds for me.

I will checkout 0.9.4 and see if that behaves differently.
However, are you able to use the latest versions of Tessera (& Quorum)? The version you are using is quite old and there are a number of improvements since then.

**Comment by Krish1979** [comment]
As Satpal suggested ,, please upgrade to latest version of Tessera and reopen the issue if you still get timeout error.

**Comment by bigstar119** [comment]
OK, i will try the latest verion. by the way my operation system is CentOS Linux release 7.3.1611.
can you test 0.9.4 use the same  operation system  with me? mybe is the operation system problem.

and what is your operation system? ubuntu redhat or something else?
