### ISSUE TITLE
Create Server type sensitive logger name for LoggingFilter

### ISSUE THREAD

**Issue by melowe** [Consensys-Incorporated/tessera#996]
The com.quorum.tessera.server.jaxrs.LoggingFilter class defined a logger and all requests are logged along with their responses.. 

The filter needs to provide a means that different servers can use different logger names. 

`com.quorum.tessera.server.jaxrs.LoggingFilter#P2P` for example or even the server url.

**Comment by nicolae-leonte-go** [comment]
It may be useful to check if we can get access to the [ResourceInfo](https://docs.oracle.com/javaee/7/api/javax/ws/rs/container/ResourceInfo.html) and log the events using the target class logger.

```
public class LoggingFilter implements ContainerRequestFilter, ContainerResponseFilter {
    @Context
    private ResourceInfo resourceInfo;
}
```
