### ISSUE TITLE
Consider supporting native-image build with GraalVM

### ISSUE THREAD

**Issue by fullkomnun** [Consensys-Incorporated/tessera#999]
Hi,

The startup times I experience with tessera are much longer (~30 seconds) than these observed when using constellation (few seconds). 
Would it be feasible to support a native-image build of the 
more lightweight tessera-simple artifact using [GraalVM](https://www.graalvm.org/)?
GraalVM has been demonstrated to reduce startup times and memory footprints among other benefits.
see: https://www.graalvm.org/docs/why-graal/
see: https://www.infoq.com/presentations/graalvm-performance/

If you have any other suggestions that might help reduce startup times, 
please advise.

**Comment by nicolae-leonte-go** [comment]
Hi,

I have performed the following test on my local machine (Ubuntu 18.04.4 LTS, AMD Ryzen 7 PRO 3700U, 16GB of RAM) and here are the results:

**Test description**

1. Start the 7nodes example (local processes/docker). 
2. Stop the tessera node1 java process.
3. Individually start tessera node1 (java -jar $TESSERA_JAR -configfile ./qdata/c1/tessera-config-09-1.json).
4. Measure (subtract) the time between the last "org.eclipse.jetty.server.Server - Started @XXXXms" and the first log statement in the console.

I should mention that there is a small delay of about 1-2 seconds from the moment the command is executed until the first log statement shows in the console (3-4 seconds for docker). 
The start times listed below do not include that.
I also believe that the "Started @XXXXms" shows the JVM uptime at the time of the log statement (which should include the delay between the process start and the first log statement).

**Results**

Local process

- open-jdk 11: 3-4 seconds

- oracle jdk 11: 3-4 seconds

Docker - the containers run on the local machine (using the image quorumengineering/tessera:0.10.3):
- open-jdk 11: 5-6 seconds

Can you provide more details about your testing environment (the way you measure start times)? What else is running on the machine besides the tessera process? 
Would you be able to start the tessera process and provide the log statemens that look similar to the following:

`2020-02-24 15:12:50.040 [main] INFO  org.eclipse.jetty.server.Server - Started @4567ms`

Thank you very much.

**Comment by fullkomnun** [comment]
Thanks for your thorough and prompt response.

I tested it both on a mid-2015 MacBook Pro and a Linux VM.
I can provide a more extensive specification but the same setup was used for both constellation and tessera yielding completely different startup times. 

All tests were performed using docker-compose, with at least 4GB allocated to docker daemon. 
I observed the time it takes for nodes of the 7node sample to become healthy
and the difference between constellation:0.3.2 and tessera:0.10.3 was so huge 
that it was apparent even without accurate measurements.

According to the logs of tessera nodes, Jetty takes a lot of time to start.
With tessera:0.10.3:
`org.eclipse.jetty.server.Server - jetty-9.4.25.v20191220; built: 2019-12-20T17:00:00.294Z; git: a9729c7e7f33a459d2616a8f9e9ba8a90f432e95; jvm 11.0.6+10
o.e.jetty.server.AbstractConnector - Started ServerConnector@5f0677f3{HTTP/1.1,[http/1.1]}{0.0.0.0:9080}
org.eclipse.jetty.server.Server - Started @134421ms
org.eclipse.jetty.server.Server - jetty-9.4.25.v20191220; built: 2019-12-20T17:00:00.294Z; git: a9729c7e7f33a459d2616a8f9e9ba8a90f432e95; jvm 11.0.6+10
o.e.jetty.server.AbstractConnector - Started UnixSocketConnector@42edde25{HTTP/1.1,[http/1.1]}{/qdata/tm/tm.ipc}
org.eclipse.jetty.server.Server - Started @154017ms
org.eclipse.jetty.server.Server - jetty-9.4.25.v20191220; built: 2019-12-20T17:00:00.294Z; git: a9729c7e7f33a459d2616a8f9e9ba8a90f432e95; jvm 11.0.6+10
o.e.jetty.server.AbstractConnector - Started ServerConnector@6212ea52{HTTP/1.1,[http/1.1]}{0.0.0.0:9000}
org.eclipse.jetty.server.Server - Started @158370ms`

It takes more than 1 minute till the last Jetty starts.
This measurement is somewhat better for V0.10.2 possibly due to the usage of a different Jetty release.

**Comment by fullkomnun** [comment]
So the measurements you provided make sense for a single tessera node but if you wish to create a cluster for e2e-testing startup times quickly degrade (while constellation scales much better).
Anyway, GraalVM can be used for making tessera nodes more container friendly so that they can be created on-the-fly quickly but that requires additional work. I'll try to play with it.

**Comment by nicolae-leonte-go** [comment]
Please let us know if you manage to get any significant reductions in startup times by creating a GraalVM native image.
Be advised that tessera makes extensive use of reflection.

**Comment by nicolae-leonte-go** [comment]
A few suggestions for speeding up your e2e testing cluser setup:
1. Reduce the number of nodes in your setup (see the numNodes parameter in the start scripts or edit the docker-compose script to reduce the number of hosts).
2. If your testing doesn't need a privacy manager (you are experimenting with quorum settings) you may skip starting tessera alltogether (start quorum with PRIVATE_CONFIG=ingore).

Tessera has some enterprise features and is designed to be flexible/configurable/extensible. At this stage we do not think that the individual tessera startup times are excessive. 
When starting lots of processes on the same machine - one should expect a reasonable slowdown.

We would really appreciate your results from experimenting with GraalVM native images.
However, at this stage, we cannot commit to providing/maintaining such a setup.
